<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 2 Análisis Exploratorio Básico | Análisis exploratorio e inferencial</title>
  <meta name="description" content="Maestría en Estadística Aplicada." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 2 Análisis Exploratorio Básico | Análisis exploratorio e inferencial" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Maestría en Estadística Aplicada." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 2 Análisis Exploratorio Básico | Análisis exploratorio e inferencial" />
  
  <meta name="twitter:description" content="Maestría en Estadística Aplicada." />
  

<meta name="author" content="Gloria Bastidas" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="diccionario-de-campos.html"/>
<link rel="next" href="pruebas-de-hipótesis-sin-desarrollar.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Libro Académico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="portada.html"><a href="portada.html"><i class="fa fa-check"></i>Portada</a></li>
<li class="chapter" data-level="" data-path="prefacio.html"><a href="prefacio.html"><i class="fa fa-check"></i>Prefacio</a>
<ul>
<li class="chapter" data-level="0.0.1" data-path="prefacio.html"><a href="prefacio.html#verificaci%C3%B3n-de-la-lectura"><i class="fa fa-check"></i><b>0.0.1</b> Verificación de la lectura</a></li>
<li class="chapter" data-level="0.0.2" data-path="prefacio.html"><a href="prefacio.html#revisi%C3%B3n-de-integridad-de-datos"><i class="fa fa-check"></i><b>0.0.2</b> Revisión de integridad de datos</a></li>
<li class="chapter" data-level="0.0.3" data-path="prefacio.html"><a href="prefacio.html#conversi%C3%B3n-de-tipos"><i class="fa fa-check"></i><b>0.0.3</b> Conversión de tipos</a></li>
<li class="chapter" data-level="0.0.4" data-path="prefacio.html"><a href="prefacio.html#consideraciones-estructurales-para-el-an%C3%A1lisis"><i class="fa fa-check"></i><b>0.0.4</b> Consideraciones estructurales para el análisis</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="diccionario-de-campos.html"><a href="diccionario-de-campos.html"><i class="fa fa-check"></i><b>1</b> Diccionario de campos</a></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html"><i class="fa fa-check"></i><b>2</b> Análisis Exploratorio Básico</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#carga-del-dataset-anal%C3%ADtico"><i class="fa fa-check"></i><b>2.1</b> Carga del dataset analítico</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-variables-respuesta"><i class="fa fa-check"></i><b>2.2</b> Análisis univariado de variables respuesta</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#costo-unitario-de-conversi%C3%B3n-o-de-transformacion"><i class="fa fa-check"></i><b>2.2.1</b> Costo unitario de conversión o de transformacion</a></li>
<li class="chapter" data-level="2.2.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#costo-unitario-de-los-insumos"><i class="fa fa-check"></i><b>2.2.2</b> Costo unitario de los insumos</a></li>
<li class="chapter" data-level="2.2.3" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#costo-unitario-total"><i class="fa fa-check"></i><b>2.2.3</b> Costo unitario total</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-predictoras-num%C3%A9ricas"><i class="fa fa-check"></i><b>2.3</b> Análisis univariado de predictoras numéricas</a></li>
<li class="chapter" data-level="2.4" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-predictoras-categ%C3%B3ricas"><i class="fa fa-check"></i><b>2.4</b> 6.4 Análisis univariado de predictoras categóricas</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-modalidad-proceso"><i class="fa fa-check"></i><b>2.4.1</b> Análisis bivariado: Modalidad proceso</a></li>
<li class="chapter" data-level="2.4.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-tipo-de-equipo"><i class="fa fa-check"></i><b>2.4.2</b> Análisis bivariado: tipo de equipo</a></li>
<li class="chapter" data-level="2.4.3" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-equipo_id"><i class="fa fa-check"></i><b>2.4.3</b> Análisis bivariado: Equipo_id</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#decisiones-metodol%C3%B3gicas-derivadas-del-eda-inicial"><i class="fa fa-check"></i><b>2.5</b> Decisiones metodológicas derivadas del EDA inicial</a></li>
<li class="chapter" data-level="2.6" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#estructura-del-espacio-operativo-sobre-el-dataset-principal"><i class="fa fa-check"></i><b>2.6</b> Estructura del espacio operativo sobre el dataset principal</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#mapa-de-combinaciones"><i class="fa fa-check"></i><b>2.6.1</b> Mapa de combinaciones</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-condicional-lo-que-revelan-los-estratos"><i class="fa fa-check"></i><b>2.7</b> Análisis condicional: lo que revelan los estratos</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#efecto-puro-de-tipo_equipo-dentro-de-x-1"><i class="fa fa-check"></i><b>2.7.1</b> Efecto puro de tipo_equipo dentro de (X, 1)</a></li>
<li class="chapter" data-level="2.7.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#efecto-de-n%C3%BAmero-de-insumos-comparaci%C3%B3n-condicional"><i class="fa fa-check"></i><b>2.7.2</b> Efecto de número de insumos: comparación condicional</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#asociaciones-num%C3%A9ricas-cuando-la-correlaci%C3%B3n-cambia-al-estratificar"><i class="fa fa-check"></i><b>2.8</b> Asociaciones numéricas: cuando la correlación cambia al estratificar</a></li>
<li class="chapter" data-level="2.9" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#caracterizaci%C3%B3n-descriptiva-de-los-subconjuntos-excluidos"><i class="fa fa-check"></i><b>2.9</b> Caracterización descriptiva de los subconjuntos excluidos</a></li>
<li class="chapter" data-level="2.10" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#estratificado"><i class="fa fa-check"></i><b>2.10</b> estratificado</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="pruebas-de-hipótesis-sin-desarrollar.html"><a href="pruebas-de-hipótesis-sin-desarrollar.html"><i class="fa fa-check"></i><b>3</b> Pruebas de Hipótesis SIN DESARROLLAR</a></li>
<li class="chapter" data-level="4" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html"><i class="fa fa-check"></i><b>4</b> Modelos SIN DESARROLLAR</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html#ajuste-del-modelo"><i class="fa fa-check"></i><b>4.1</b> Ajuste del modelo</a></li>
<li class="chapter" data-level="4.2" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html#medidas-de-ajuste"><i class="fa fa-check"></i><b>4.2</b> Medidas de ajuste</a></li>
<li class="chapter" data-level="4.3" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html#gr%C3%A1fico-de-observados-vs-ajustados"><i class="fa fa-check"></i><b>4.3</b> Gráfico de observados vs ajustados</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="conclusión.html"><a href="conclusión.html"><i class="fa fa-check"></i><b>5</b> Conclusión</a></li>
<li class="chapter" data-level="6" data-path="bibliografía.html"><a href="bibliografía.html"><i class="fa fa-check"></i><b>6</b> Bibliografía</a></li>
<li class="divider"></li>
<li><a href="https://github.com/">Publicado con GitHub Pages</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis exploratorio e inferencial</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-exploratorio-básico" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Capítulo 2</span> Análisis Exploratorio Básico<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-exploratorio-b%C3%A1sico" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="carga-del-dataset-analítico" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Carga del dataset analítico<a href="análisis-exploratorio-básico.html#carga-del-dataset-anal%C3%ADtico" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se parte del dataset depurado en el capítulo de metodología (395 órdenes de producción con tipos ajustados). La limpieza previa ya eliminó errores de digitación y validó la integridad de los registros; este capítulo se concentra en entender qué dicen esos datos.</p>
<p>El dataset contiene 395 órdenes de producción y 17 variables.</p>
</div>
<div id="análisis-univariado-de-variables-respuesta" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Análisis univariado de variables respuesta<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-variables-respuesta" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las tres variables respuesta del estudio son <code>costo_transformacion</code> (costo de conversión por unidad producida), <code>costo_insumo</code> (costo de materias primas por unidad producida) y su agregado <code>costo_unitario_total</code>. Se analizan en paralelo porque responden a lógicas operativas distintas: el costo de transformación refleja eficiencia de máquina y proceso, mientras que el costo de insumo refleja decisiones de formulación y consumo de materias primas.</p>
<div id="costo-unitario-de-conversión-o-de-transformacion" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Costo unitario de conversión o de transformacion<a href="análisis-exploratorio-básico.html#costo-unitario-de-conversi%C3%B3n-o-de-transformacion" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table class="table table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ck-resumen-ct">Table 2.1: </span>Resumen del costo de transformación
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
395
</td>
<td style="text-align:right;">
29.93986
</td>
<td style="text-align:right;">
15.25873
</td>
<td style="text-align:right;">
29.0901
</td>
<td style="text-align:right;">
2.76611
</td>
<td style="text-align:right;">
97.1848
</td>
<td style="text-align:right;">
21.90816
</td>
<td style="text-align:right;">
36.44523
</td>
<td style="text-align:right;">
14.53708
</td>
</tr>
</tbody>
</table>
<p>La variable <code>costo_transformacion</code> se analizó a partir de 395 órdenes de producción.
Se obtuvo un costo medio de conversión por unidad de 29.94 UM/unidad (DS = 15.26 UM/unidad), con un coeficiente de variación de 51%. El 50% de las órdenes presenta un costo de conversión por debajo de 29.09 UM/unidad.
La desviación estándar alcanza 15.26, lo que equivale a un coeficiente de variación de 51%. Quiere decir que los costos fluctúan de manera importante respecto al promedio.</p>
<p>El rango intercuartílico (14.54) indica que la mitad central de los datos se sitúa en un intervalo relativamente acotado, lo que describe el comportamiento típico del proceso.
Sin embargo, los extremos revela algo distinto. Mientras el valor mínimo (2.77) se mantiene dentro de lo esperado, el máximo (97.18) se encuentra considerablemente alejado del resto. Este comportamiento puede sugerir la presencia de valores atípicos en la parte superior de la distribución, generando una cola hacia la derecha.
En términos prácticos, esto significa que la mayoría de los procesos operan en niveles de costo relativamente estables, pero existen casos puntuales significativamente más costosos. Estos valores extremos pueden responder a procesos más complejos o a posibles inconsistencias en los datos, por lo que requieren un análisis específico antes de su inclusión en modelos o decisiones operativas.</p>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/ck_hist_ct-1.png" alt="" width="864" /></p>
<p>El núcleo de la distribución se concentra claramente alrededor de r round(ct_media,2), con una densidad máxima cercana a los 25–30 UM. Esta región coincide con la mediana (r round(ct_med,2)) y el rango intercuartílico.
La forma de la distribución no es simétrica. Se observa una cola derecha prolongada, que se extiende hasta valores cercanos a r round(ct_max,0). Esta asimetría implica que, aunque la mayoría de los costos son moderados, existe una proporción pequeña de observaciones con costos significativamente más altos.
Adicionalmente, aparece un leve segundo abultamiento en valores bajos (≈ 5–15 UM). Esto sugiere la posible existencia de subgrupos dentro del proceso, es decir, no todos los registros provienen del mismo mecanismo generador de costos.</p>
<p>Podrían coexistir:
- procesos simples o de baja complejidad (costos bajos)
- procesos estándar (zona central)
- procesos excepcionales o más complejos (cola derecha)</p>
<p>En términos operativos, el sistema no solo presenta variabilidad, sino también estructura interna: no es un proceso homogéneo, sino una mezcla de dinámicas distintas que conviene separar antes de cualquier inferencia o optimización.</p>
<p>El bigote superior se extiende hasta un cierto punto, pero inmediatamente aparecen múltiples observaciones por encima, marcadas en rojo. Estos son outliers superiores, y no son pocos ni aislados: forman un grupo visible.
Existe una subpoblación de costos altos. Es decir no son casos extremos que sean puntuales. En la parte inferior no se observan outliers relevantes. El mínimo está dentro del rango esperado
El boxplot confirma la dispersión y evidencia que el fenómeno clave no es la variabilidad general, sino la existencia de una dinámica diferenciada en costos altos, que requiere segmentación o modelado específico.</p>
</div>
<div id="costo-unitario-de-los-insumos" class="section level3 hasAnchor" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Costo unitario de los insumos<a href="análisis-exploratorio-básico.html#costo-unitario-de-los-insumos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<table class="table table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ck-hist-ci">Table 2.2: </span>Resumen del costo de insumo
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
395
</td>
<td style="text-align:right;">
5.048482
</td>
<td style="text-align:right;">
4.419278
</td>
<td style="text-align:right;">
4.184607
</td>
<td style="text-align:right;">
0.0136519
</td>
<td style="text-align:right;">
46.21884
</td>
<td style="text-align:right;">
2.427897
</td>
<td style="text-align:right;">
6.211323
</td>
<td style="text-align:right;">
3.783426
</td>
</tr>
</tbody>
</table>
<p>El costo de insumo promedio es de 5.05 UM/unidad (DS = 4.42 UM/unidad), con un coeficiente de variación de 87.5%. El 50% de las órdenes tiene un costo de insumo por debajo de 4.18 UM/unidad, con un mínimo de 0.01 y un máximo de 46.22 UM/unidad. El rango intercuartílico es de 3.78 UM/unidad.
El comportamiento típico se concentra en valores bajos. La mayoría de los insumos se ubican en niveles reducidos de costo, mientras que la media (r round(ci_media,2)) es superior, lo que evidencia la influencia de valores más altos sobre el promedio. Esta diferencia confirma una asimetría positiva: pocos insumos concentran costos considerablemente mayores.
El rango intercuartílico (r round(ci_iqr,2)) delimita el comportamiento típico: el 50% central de los costos se sitúa en un intervalo relativamente acotado, lo que sugiere que existe un conjunto dominante de insumos de bajo costo. Sin embargo, este núcleo convive con una cola derecha extensa.
En resumen:
- comportamiento homogéneo
- un grupo mayoritario de insumos de bajo costo
- un conjunto reducido de insumos de costo medio
- pocos insumos de alto impacto económico</p>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/ck_hist_box_ci-1.png" alt="" width="1056" /></p>
</div>
<div id="costo-unitario-total" class="section level3 hasAnchor" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Costo unitario total<a href="análisis-exploratorio-básico.html#costo-unitario-total" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La variable <code>costo_unitario_total</code> se deriva como la suma de <code>costo_transformacion</code> y <code>costo_insumo</code>, y representa el costo total por unidad de producto.</p>
<table class="table table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ck-resumen-ctot">Table 2.3: </span>Resumen del costo unitario total
</caption>
<thead>
<tr>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
395
</td>
<td style="text-align:right;">
34.98835
</td>
<td style="text-align:right;">
17.28567
</td>
<td style="text-align:right;">
33.63643
</td>
<td style="text-align:right;">
4.301429
</td>
<td style="text-align:right;">
111.7165
</td>
<td style="text-align:right;">
25.60903
</td>
<td style="text-align:right;">
41.68937
</td>
<td style="text-align:right;">
16.08034
</td>
</tr>
</tbody>
</table>
<p>El costo unitario total promedio es de 34.99 UM/unidad , la cercanía relativa entre ambas indica que, aunque existe asimetría, el núcleo del sistema está bien definido. Sin embargo, la media se mantiene por encima de la mediana, lo que confirma la presencia de una cola derecha..
Un coeficiente de variación de 49.4% (DS = 17.29), la variabilidad del costo total no es despreciable . De este promedio, el 85.6% corresponde al costo de transformación y el 14.4% al costo de insumo.
El 50% de las órdenes presenta un costo unitario total por debajo de 33.64 UM/unidad, con un rango entre 4.3 y 111.72.
El boxplot confirma la presencia de outliers superiores múltiples, no aislados. Estos valores altos no corresponden a ruido aleatorio, sino a una fracción del sistema que sistemáticamente incurre en costos elevados.</p>
<p>Descomposición del costo total:
- Costo de transformación representa aproximadamente r prop_ct% del total
- Costo de insumos representa aproximadamente r prop_ci%
Claramente el componente dominante del costo total es el proceso de transformación, mientras que los insumos, aunque más variables, tienen menor peso relativo en el agregado.</p>
<p>El sistema productivo opera mayoritariamente en un rango de costos relativamente estable, pero está condicionado por una fracción de casos con costos significativamente más altos. Estos casos no son marginales y deben interpretarse como parte de la estructura del proceso, no como anomalías aisladas. La clave analítica no está en el promedio, sino en entender qué condiciones generan esos costos elevados y cómo se relacionan con los componentes del costo total.</p>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/ck_hist_box_ctot-1.png" alt="" width="1056" /></p>
<p>El costo unitario total hereda la asimetría de sus dos componentes. Cualquier iniciativa de reducción de costos que se concentre solo en el componente de insumos tendrá un techo muy bajo. La palanca real está en la transformación.</p>
<div class="alert alert-info">
<p>Los tres costos presentan distribuciones asimétricas con cola derecha pronunciada. En costo_transformacion se observa además un leve segundo abultamiento hacia valores bajos (5–15 UM), que rompe el patrón unimodal esperado.
Se observa una bimodalidad leve, es decir un segundo abultamiento en el rango bajo (≈5–15 UM), separado del principal que está alrededor ~25–30 UM. Esto podría indicar que los datos no provienen de un proceso único, sino de dos o más procesos distintos mezclados.
En consecuencia, el sistema productivo puede no ser un único proceso homogéneo, sino una mezcla de regímenes operativos con dinámicas de costo distintas. Si esto es cierto, los estadísticos agregados están ocultando diferencias estructurales importantes</p>
</div>
</div>
</div>
<div id="análisis-univariado-de-predictoras-numéricas" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Análisis univariado de predictoras numéricas<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-predictoras-num%C3%A9ricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las variables numéricas predictoras son <code>volumen_lote</code>, <code>duracion_proceso</code>, <code>cantidad_insumo_1</code> y <code>cantidad_insumo_2</code>.</p>
<table class="table table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:ck-resumen-num-predictoras">Table 2.4: </span>Resumen descriptivo de las variables numéricas seleccionadas
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
volumen_lote
</td>
<td style="text-align:right;">
395
</td>
<td style="text-align:right;">
2739.03
</td>
<td style="text-align:right;">
2346.76
</td>
<td style="text-align:right;">
1989
</td>
<td style="text-align:right;">
1e+02
</td>
<td style="text-align:right;">
13300
</td>
<td style="text-align:right;">
1226.00
</td>
<td style="text-align:right;">
3289
</td>
<td style="text-align:right;">
2063.00
</td>
</tr>
<tr>
<td style="text-align:left;">
duracion_proceso
</td>
<td style="text-align:right;">
395
</td>
<td style="text-align:right;">
115.79
</td>
<td style="text-align:right;">
82.59
</td>
<td style="text-align:right;">
100
</td>
<td style="text-align:right;">
3e+00
</td>
<td style="text-align:right;">
482
</td>
<td style="text-align:right;">
60.00
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
90.00
</td>
</tr>
<tr>
<td style="text-align:left;">
cantidad_insumo_1
</td>
<td style="text-align:right;">
395
</td>
<td style="text-align:right;">
2.29
</td>
<td style="text-align:right;">
1.90
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
5e-02
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2.00
</td>
</tr>
<tr>
<td style="text-align:left;">
cantidad_insumo_2
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
1.43
</td>
<td style="text-align:right;">
1.08
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5e-02
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0.75
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1.25
</td>
</tr>
</tbody>
</table>
<p>No son variables independientes: describen distintas dimensiones del mismo proceso productivo.
- Volumen de lote, es la variable más heterogénea. La media supera claramente a la mediana, lo que indica asimetría positiva. El rango es muy amplio (100 a 13300) y el IQR (2063) es elevado, señal de que incluso el comportamiento “típico” presenta alta dispersión. el proceso opera con lotes muy dispares, dependiendo de los pedidos de los clientes , el proceso es make to order. No hay un tamaño estándar dominante.
- Duración del proceso, es heterogéneo también pero más controlado. La media es superior a la mediana, nuevamente cola derecha. El IQR muestra que la mitad de los procesos se concentra entre 60 y 150 horas, lo que define un rango operativo razonablemente estable. Sin embargo, el máximo de 482 horas apunta a procesos excepcionalmente largos.
- Cantidad de insumo 1, comportamiento más discreto y concentrado. La mediana es 2 y el IQR es 2, lo que indica que la mayoría de los casos utiliza entre 1 y 3 unidades. La media (2.29) ligeramente superior a la mediana sugiere algunos valores altos, pero sin una dispersión extrema. Esta variable refleja un consumo relativamente estable y predecible, con variaciones moderadas.
- Cantidad de insumo 2: Tiene menor número de observaciones, no todos las ordenes llevan insumo 2. Su mediana es 1 y el IQR es 1.25, lo que muestra una concentración aún mayor que en el insumo 1. La dispersión es baja y los valores extremos (máximo 7) son menos pronunciados. Esto sugiere que el segundo insumo actúa como un componente opcional o complementario, con consumo bajo y controlado.</p>
<p>La principal fuente de heterogeneidad no está en los insumos, sino en el tamaño de los lotes y la duración de los procesos. Esto sugiere que cualquier modelamiento o mejora operativa debe centrarse en segmentar por escala de producción y complejidad del proceso, más que en el consumo de insumos.</p>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/box_num_predictoras-1.png" alt="" width="1056" /></p>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/hist_num_predictoras-1.png" alt="" width="1056" /></p>
<div class="alert alert-info">
<p>Visualmente, la fuente real de heterogeneidad no está en los insumos, sino en cómo y cuánto se produce. Esto implica que cualquier análisis o modelo que ignore la escala (volumen) o la complejidad (duración) va a estar mal especificado.
El sistema produce lotes de escalas muy distintas (entre 100 y 13.300 unidades), con duraciones que van de 3 a 482 horas. Esta heterogeneidad refleja una lógica de producción “make-to-order” donde cada orden responde a un pedido específico. El tamaño estándar de lote no existe. El proceso no puede optimizarse con reglas uniformes; requerirá segmentación por rangos de producción.
→ Heterogeneidad en volumen y duración, consumo de insumos estable</p>
</div>
</div>
<div id="análisis-univariado-de-predictoras-categóricas" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> 6.4 Análisis univariado de predictoras categóricas<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-predictoras-categ%C3%B3ricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<pre><code>  → Concentración en A1 (73%), cardinalidad variable entre categóricas</code></pre>
<p>## 6.5 Análisis bivariado marginal
### 6.5.1 Correlaciones Pearson y Spearman
### 6.5.2 Diagramas de dispersión
### 6.5.3 Boxplots de costo por tipo_equipo, modalidad, num_insumos
→ Diferencias muy grandes entre tipos de equipo y modalidades
## 6.6 Señales de heterogeneidad estructural
### 6.6.1 Las distribuciones condicionales no son uniformes
### 6.6.2 Tabulación cruzada tipo_equipo × modalidad × num_insumos
### 6.6.3 Descubrimiento: el espacio operativo está truncado
## 6.7 Implicaciones metodológicas del descubrimiento
### 6.7.1 Por qué el análisis marginal puede ser engañoso (confounding)
### 6.7.2 Decisiones de exclusión justificadas
- Exclusión de modalidad Z (n=14)
- Exclusión de tipo_equipo C3 (n=8)
- Identificación de A1 como configuración universal
## 6.8 Generación del dataset principal
6.8.1 Filtrado y exportación (data_costos_principal.csv / .rds)
6.8.2 Verificación del dataset resultante
## 6.9 Cierre: qué sabemos, qué no sabemos, qué sigue
→ Hipótesis que justifican el análisis estratificado</p>
<div id="análisis-bivariado-modalidad-proceso" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Análisis bivariado: Modalidad proceso<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-modalidad-proceso" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="análisis-exploratorio-básico.html#cb22-1" tabindex="-1"></a>resumen_bivariado_cc_modproceso <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="análisis-exploratorio-básico.html#cb22-2" tabindex="-1"></a>  <span class="fu">group_by</span>(modalidad_proceso) <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="análisis-exploratorio-básico.html#cb22-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb22-4"><a href="análisis-exploratorio-básico.html#cb22-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(costo_transformacion),</span>
<span id="cb22-5"><a href="análisis-exploratorio-básico.html#cb22-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb22-6"><a href="análisis-exploratorio-básico.html#cb22-6" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(costo_transformacion),</span>
<span id="cb22-7"><a href="análisis-exploratorio-básico.html#cb22-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_transformacion),</span>
<span id="cb22-8"><a href="análisis-exploratorio-básico.html#cb22-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(costo_transformacion),</span>
<span id="cb22-9"><a href="análisis-exploratorio-básico.html#cb22-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(costo_transformacion),</span>
<span id="cb22-10"><a href="análisis-exploratorio-básico.html#cb22-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(costo_transformacion, <span class="fl">0.25</span>),</span>
<span id="cb22-11"><a href="análisis-exploratorio-básico.html#cb22-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(costo_transformacion, <span class="fl">0.75</span>),</span>
<span id="cb22-12"><a href="análisis-exploratorio-básico.html#cb22-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(costo_transformacion),</span>
<span id="cb22-13"><a href="análisis-exploratorio-básico.html#cb22-13" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb22-14"><a href="análisis-exploratorio-básico.html#cb22-14" tabindex="-1"></a>  )</span>
<span id="cb22-15"><a href="análisis-exploratorio-básico.html#cb22-15" tabindex="-1"></a></span>
<span id="cb22-16"><a href="análisis-exploratorio-básico.html#cb22-16" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(resumen_bivariado_cc_modproceso , <span class="at">caption =</span> <span class="st">&quot;Resumen Bivariado costos de transformación por modalidad de proceso&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-17"><a href="análisis-exploratorio-básico.html#cb22-17" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_cc_modproceso)(#tab:bivariado_cc_modproceso)Resumen Bivariado costos de transformación por modalidad de proceso
</caption>
<thead>
<tr>
<th style="text-align:left;">
modalidad_proceso
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
27.90974
</td>
<td style="text-align:right;">
17.87045
</td>
<td style="text-align:right;">
27.15583
</td>
<td style="text-align:right;">
2.766110
</td>
<td style="text-align:right;">
97.18480
</td>
<td style="text-align:right;">
12.36344
</td>
<td style="text-align:right;">
35.13867
</td>
<td style="text-align:right;">
22.77523
</td>
</tr>
<tr>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
31.39504
</td>
<td style="text-align:right;">
10.51311
</td>
<td style="text-align:right;">
29.56235
</td>
<td style="text-align:right;">
5.093602
</td>
<td style="text-align:right;">
76.49633
</td>
<td style="text-align:right;">
24.79461
</td>
<td style="text-align:right;">
36.44523
</td>
<td style="text-align:right;">
11.65063
</td>
</tr>
<tr>
<td style="text-align:left;">
Z
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
41.62190
</td>
<td style="text-align:right;">
17.33280
</td>
<td style="text-align:right;">
38.88523
</td>
<td style="text-align:right;">
23.124712
</td>
<td style="text-align:right;">
92.17387
</td>
<td style="text-align:right;">
33.02403
</td>
<td style="text-align:right;">
43.81498
</td>
<td style="text-align:right;">
10.79095
</td>
</tr>
</tbody>
</table>
<p>La modalidad Z es una combinación operativa de X y Y.</p>
<p>En costo de transformación, se observa un gradiente en la media que va de X a Y y luego a Z, pero el salto no es lineal.:
X ≈ 27.9 &lt; Y ≈ 31.4 &lt; Z ≈ 41.6
La mediana también confirma ese patrón (27.1 → 29.5 → 38.8).</p>
<ul>
<li>X tiene alta variabilidad (ds ≈ 17.9, IQR amplio). Es un proceso inestable.</li>
<li>Y es más controlado (ds ≈ 10.5, IQR más estrecho).</li>
<li>Z tiene dispersión alta en términos absolutos, pero IQR relativamente contenido. Esto indica que el costo base es alto de forma consistente, no solo por outliers.</li>
</ul>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="análisis-exploratorio-básico.html#cb23-1" tabindex="-1"></a>resumen_bivariado_ci_modproceso <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="análisis-exploratorio-básico.html#cb23-2" tabindex="-1"></a>  <span class="fu">group_by</span>(modalidad_proceso) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="análisis-exploratorio-básico.html#cb23-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb23-4"><a href="análisis-exploratorio-básico.html#cb23-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(costo_insumo),</span>
<span id="cb23-5"><a href="análisis-exploratorio-básico.html#cb23-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_insumo),</span>
<span id="cb23-6"><a href="análisis-exploratorio-básico.html#cb23-6" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(costo_insumo),</span>
<span id="cb23-7"><a href="análisis-exploratorio-básico.html#cb23-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_insumo),</span>
<span id="cb23-8"><a href="análisis-exploratorio-básico.html#cb23-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(costo_insumo),</span>
<span id="cb23-9"><a href="análisis-exploratorio-básico.html#cb23-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(costo_insumo),</span>
<span id="cb23-10"><a href="análisis-exploratorio-básico.html#cb23-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(costo_insumo, <span class="fl">0.25</span>),</span>
<span id="cb23-11"><a href="análisis-exploratorio-básico.html#cb23-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(costo_insumo, <span class="fl">0.75</span>),</span>
<span id="cb23-12"><a href="análisis-exploratorio-básico.html#cb23-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(costo_insumo),</span>
<span id="cb23-13"><a href="análisis-exploratorio-básico.html#cb23-13" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb23-14"><a href="análisis-exploratorio-básico.html#cb23-14" tabindex="-1"></a>  )</span>
<span id="cb23-15"><a href="análisis-exploratorio-básico.html#cb23-15" tabindex="-1"></a></span>
<span id="cb23-16"><a href="análisis-exploratorio-básico.html#cb23-16" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>(resumen_bivariado_ci_modproceso , <span class="at">caption =</span> <span class="st">&quot;Resumen Bivariado costos de insumo por modalidad de proceso&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-17"><a href="análisis-exploratorio-básico.html#cb23-17" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_ci_modproceso)(#tab:bivariado_ci_modproceso)Resumen Bivariado costos de insumo por modalidad de proceso
</caption>
<thead>
<tr>
<th style="text-align:left;">
modalidad_proceso
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
X
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
4.795688
</td>
<td style="text-align:right;">
4.983349
</td>
<td style="text-align:right;">
3.901745
</td>
<td style="text-align:right;">
0.0136519
</td>
<td style="text-align:right;">
46.21884
</td>
<td style="text-align:right;">
2.046081
</td>
<td style="text-align:right;">
5.885855
</td>
<td style="text-align:right;">
3.839774
</td>
</tr>
<tr>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
5.200829
</td>
<td style="text-align:right;">
3.602861
</td>
<td style="text-align:right;">
4.324094
</td>
<td style="text-align:right;">
0.1148000
</td>
<td style="text-align:right;">
21.80388
</td>
<td style="text-align:right;">
2.666188
</td>
<td style="text-align:right;">
6.586521
</td>
<td style="text-align:right;">
3.920333
</td>
</tr>
<tr>
<td style="text-align:left;">
Z
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
6.863816
</td>
<td style="text-align:right;">
4.656808
</td>
<td style="text-align:right;">
4.981695
</td>
<td style="text-align:right;">
2.3523921
</td>
<td style="text-align:right;">
17.18095
</td>
<td style="text-align:right;">
4.093923
</td>
<td style="text-align:right;">
8.363485
</td>
<td style="text-align:right;">
4.269563
</td>
</tr>
</tbody>
</table>
<p>En costo de insumo, el patrón es más suave:
X ≈ 4.80, Y ≈ 5.20, Z ≈ 6.86</p>
<p>La mediana de Z (≈ 4.98) está cerca de Y, el aumento en la media puede provenir de algunos valores altos .</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="análisis-exploratorio-básico.html#cb24-1" tabindex="-1"></a>box_ct_mod_proceso <span class="ot">&lt;-</span>datos <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="análisis-exploratorio-básico.html#cb24-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> modalidad_proceso, <span class="at">y =</span> costo_transformacion)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="análisis-exploratorio-básico.html#cb24-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#87CEFA&quot;</span>, <span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb24-4"><a href="análisis-exploratorio-básico.html#cb24-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-5"><a href="análisis-exploratorio-básico.html#cb24-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de equipo&quot;</span>,</span>
<span id="cb24-6"><a href="análisis-exploratorio-básico.html#cb24-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Costo de transformación (UM/unidad)&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-7"><a href="análisis-exploratorio-básico.html#cb24-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb24-8"><a href="análisis-exploratorio-básico.html#cb24-8" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Costo de transformación por modalidad de proceso &quot;</span>)</span>
<span id="cb24-9"><a href="análisis-exploratorio-básico.html#cb24-9" tabindex="-1"></a></span>
<span id="cb24-10"><a href="análisis-exploratorio-básico.html#cb24-10" tabindex="-1"></a></span>
<span id="cb24-11"><a href="análisis-exploratorio-básico.html#cb24-11" tabindex="-1"></a>box_ci_mod_proceso <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb24-12"><a href="análisis-exploratorio-básico.html#cb24-12" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> modalidad_proceso, <span class="at">y =</span> costo_insumo)) <span class="sc">+</span></span>
<span id="cb24-13"><a href="análisis-exploratorio-básico.html#cb24-13" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#b2df8a&quot;</span>, <span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb24-14"><a href="análisis-exploratorio-básico.html#cb24-14" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-15"><a href="análisis-exploratorio-básico.html#cb24-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Modalidad de proceso&quot;</span>,</span>
<span id="cb24-16"><a href="análisis-exploratorio-básico.html#cb24-16" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Costo de insumo (UM/unidad)&quot;</span>) <span class="sc">+</span></span>
<span id="cb24-17"><a href="análisis-exploratorio-básico.html#cb24-17" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb24-18"><a href="análisis-exploratorio-básico.html#cb24-18" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Costo de insumo por modalidad de proceso&quot;</span>)</span>
<span id="cb24-19"><a href="análisis-exploratorio-básico.html#cb24-19" tabindex="-1"></a></span>
<span id="cb24-20"><a href="análisis-exploratorio-básico.html#cb24-20" tabindex="-1"></a>box_ct_mod_proceso <span class="sc">+</span> box_ci_mod_proceso</span></code></pre></div>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/box_bivariado_mod_proceso-1.png" alt="" width="864" /></p>
<p>El sobrecosto de Z proviene principalmente de transformación, no de insumo, y además no es lineal. Es un fenómeno de interacción entre procesos, no de suma simple.</p>
<p>En cambio, el costo de insumo sube poco y de forma relativamente lógica. Eso confirma que el problema no está en materiales, sino en cómo se ejecuta el proceso combinado.</p>
<p>El tamaño de muestra de Z es bajo (n = 14).</p>
<p>Y es más estable y ligeramente más costoso que X. Pero X es más volátil.</p>
</div>
<div id="análisis-bivariado-tipo-de-equipo" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Análisis bivariado: tipo de equipo<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-tipo-de-equipo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="análisis-exploratorio-básico.html#cb25-1" tabindex="-1"></a>vars_cat <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;tipo_equipo&quot;</span>, <span class="st">&quot;equipo_id&quot;</span>, <span class="st">&quot;categoria_producto&quot;</span>, </span>
<span id="cb25-2"><a href="análisis-exploratorio-básico.html#cb25-2" tabindex="-1"></a>              <span class="st">&quot;modalidad_proceso&quot;</span>, <span class="st">&quot;num_insumos&quot;</span>, <span class="st">&quot;insumo_1&quot;</span>, <span class="st">&quot;insumo_2&quot;</span>)</span>
<span id="cb25-3"><a href="análisis-exploratorio-básico.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="análisis-exploratorio-básico.html#cb25-4" tabindex="-1"></a>tabla_cat <span class="ot">&lt;-</span> <span class="fu">map_dfr</span>(vars_cat, <span class="cf">function</span>(v) {</span>
<span id="cb25-5"><a href="análisis-exploratorio-básico.html#cb25-5" tabindex="-1"></a>  datos <span class="sc">%&gt;%</span></span>
<span id="cb25-6"><a href="análisis-exploratorio-básico.html#cb25-6" tabindex="-1"></a>    <span class="fu">count</span>(.data[[v]], <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-7"><a href="análisis-exploratorio-básico.html#cb25-7" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb25-8"><a href="análisis-exploratorio-básico.html#cb25-8" tabindex="-1"></a>      <span class="at">Porcentaje =</span> (Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb25-9"><a href="análisis-exploratorio-básico.html#cb25-9" tabindex="-1"></a>      <span class="at">Variable =</span> v,</span>
<span id="cb25-10"><a href="análisis-exploratorio-básico.html#cb25-10" tabindex="-1"></a>      <span class="at">Categoria =</span> <span class="fu">as.character</span>(.data[[v]])</span>
<span id="cb25-11"><a href="análisis-exploratorio-básico.html#cb25-11" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb25-12"><a href="análisis-exploratorio-básico.html#cb25-12" tabindex="-1"></a>    <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb25-13"><a href="análisis-exploratorio-básico.html#cb25-13" tabindex="-1"></a>}) <span class="sc">%&gt;%</span></span>
<span id="cb25-14"><a href="análisis-exploratorio-básico.html#cb25-14" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Porcentaje, <span class="dv">2</span>))</span>
<span id="cb25-15"><a href="análisis-exploratorio-básico.html#cb25-15" tabindex="-1"></a></span>
<span id="cb25-16"><a href="análisis-exploratorio-básico.html#cb25-16" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tabla_cat, <span class="at">caption =</span> <span class="st">&quot;Resumen descriptivo de las variables categóricas seleccionadas&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-17"><a href="análisis-exploratorio-básico.html#cb25-17" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:tabla_res_categoricas)(#tab:tabla_res_categoricas)Resumen descriptivo de las variables categóricas seleccionadas
</caption>
<thead>
<tr>
<th style="text-align:left;">
Variable
</th>
<th style="text-align:left;">
Categoria
</th>
<th style="text-align:right;">
Frecuencia
</th>
<th style="text-align:right;">
Porcentaje
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
tipo_equipo
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
287
</td>
<td style="text-align:right;">
72.66
</td>
</tr>
<tr>
<td style="text-align:left;">
tipo_equipo
</td>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
11.39
</td>
</tr>
<tr>
<td style="text-align:left;">
tipo_equipo
</td>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
2.03
</td>
</tr>
<tr>
<td style="text-align:left;">
tipo_equipo
</td>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
13.92
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M02
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
11.39
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M04
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1.01
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M05
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
7.85
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M08
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
8.61
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M09
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
10.13
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M11
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1.01
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M12
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
6.08
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M13
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
9.11
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M14
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
10.89
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M15
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
10.89
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M16
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
11.65
</td>
</tr>
<tr>
<td style="text-align:left;">
equipo_id
</td>
<td style="text-align:left;">
M17
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
11.39
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
2.28
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
2.28
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
3
</td>
<td style="text-align:right;">
74
</td>
<td style="text-align:right;">
18.73
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
4
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
7.59
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
5
</td>
<td style="text-align:right;">
246
</td>
<td style="text-align:right;">
62.28
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
6
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0.25
</td>
</tr>
<tr>
<td style="text-align:left;">
categoria_producto
</td>
<td style="text-align:left;">
7
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
6.58
</td>
</tr>
<tr>
<td style="text-align:left;">
modalidad_proceso
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:right;">
206
</td>
<td style="text-align:right;">
52.15
</td>
</tr>
<tr>
<td style="text-align:left;">
modalidad_proceso
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
44.30
</td>
</tr>
<tr>
<td style="text-align:left;">
modalidad_proceso
</td>
<td style="text-align:left;">
Z
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
3.54
</td>
</tr>
<tr>
<td style="text-align:left;">
num_insumos
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
271
</td>
<td style="text-align:right;">
68.61
</td>
</tr>
<tr>
<td style="text-align:left;">
num_insumos
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
124
</td>
<td style="text-align:right;">
31.39
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_1
</td>
<td style="text-align:left;">
A_T
</td>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
9.62
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_1
</td>
<td style="text-align:left;">
B_T
</td>
<td style="text-align:right;">
173
</td>
<td style="text-align:right;">
43.80
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_1
</td>
<td style="text-align:left;">
N_O
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
10.89
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_1
</td>
<td style="text-align:left;">
N_T
</td>
<td style="text-align:right;">
114
</td>
<td style="text-align:right;">
28.86
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_1
</td>
<td style="text-align:left;">
R_T
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
3.04
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_1
</td>
<td style="text-align:left;">
V_T
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
3.80
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
A_T
</td>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
5.06
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
B_T
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
3.80
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
N_O
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
5.82
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
N_T
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
6.84
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
R_T
</td>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
6.33
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
sin_segundo_insumo
</td>
<td style="text-align:right;">
271
</td>
<td style="text-align:right;">
68.61
</td>
</tr>
<tr>
<td style="text-align:left;">
insumo_2
</td>
<td style="text-align:left;">
V_T
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
3.54
</td>
</tr>
</tbody>
</table>
<p>Tipo de equipo: La categoría A1 concentra el 72.7% de las observaciones. Significa que cualquier estadístico global del sistema está dominado por el comportamiento de un solo tipo de equipo. Cuando un análisis habla del “costo promedio del sistema”, en realidad habla —en un 73%— del costo promedio de A1.</p>
<p>Las demás categorías (B2, D4, C3) tienen participaciones mucho menores, lo que implica posible sesgo en análisis globales si no se segmenta y riesgo de conclusiones dominadas por A1.
C3 (2.03%) es prácticamente marginal.
Equipo específico (equipo_id): Distribución es más fragmentada, pero aún desigual. algunos equipos concentran entre 8% y 11% (M02, M09, M08), otros son casi irrelevantes (~1%)
El sistema no es balanceado, fuerte concentración en tipo A1
Existe heterogeneidad operativa, → distintos equipos tienen niveles de uso muy distintos
Cualquier modelo debe considerar tipo_equipo como variable explicativa clave, equipo_id puede capturar efectos más finos (variabilidad intra-tipo) , Comparaciones entre categorías pequeñas pueden ser inestables (bajo n)</p>
<p>El sistema está estructurado alrededor de un tipo dominante (A1) y un subconjunto reducido de equipos con alta actividad. La variabilidad observada en costos, duración o volumen probablemente está condicionada por esta estructura, no solo por aleatoriedad.</p>
<p>El tipo de equipo dominante es A1, que concentra el 72.66% de las órdenes. La variable <code>equipo_id</code> tiene 12 niveles distintos y <code>categoria_producto</code> tiene 7 niveles, lo cual exigirá tratamiento cuidadoso en los análisis inferenciales posteriores para evitar celdas con pocas observaciones.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="análisis-exploratorio-básico.html#cb26-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb26-2"><a href="análisis-exploratorio-básico.html#cb26-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb26-3"><a href="análisis-exploratorio-básico.html#cb26-3" tabindex="-1"></a></span>
<span id="cb26-4"><a href="análisis-exploratorio-básico.html#cb26-4" tabindex="-1"></a>tabla_plot <span class="ot">&lt;-</span> tabla_cat <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="análisis-exploratorio-básico.html#cb26-5" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb26-6"><a href="análisis-exploratorio-básico.html#cb26-6" tabindex="-1"></a></span>
<span id="cb26-7"><a href="análisis-exploratorio-básico.html#cb26-7" tabindex="-1"></a><span class="co"># 2. Generación del gráfico facetado (2 columnas x 4 filas)</span></span>
<span id="cb26-8"><a href="análisis-exploratorio-básico.html#cb26-8" tabindex="-1"></a><span class="fu">ggplot</span>(tabla_plot, <span class="fu">aes</span>(<span class="at">x =</span> Categoria, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb26-9"><a href="análisis-exploratorio-básico.html#cb26-9" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb26-10"><a href="análisis-exploratorio-básico.html#cb26-10" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb26-11"><a href="análisis-exploratorio-básico.html#cb26-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.2</span>))) <span class="sc">+</span></span>
<span id="cb26-12"><a href="análisis-exploratorio-básico.html#cb26-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb26-13"><a href="análisis-exploratorio-básico.html#cb26-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Categoría&quot;</span>, </span>
<span id="cb26-14"><a href="análisis-exploratorio-básico.html#cb26-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span>,</span>
<span id="cb26-15"><a href="análisis-exploratorio-básico.html#cb26-15" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de Variables Categóricas&quot;</span></span>
<span id="cb26-16"><a href="análisis-exploratorio-básico.html#cb26-16" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-17"><a href="análisis-exploratorio-básico.html#cb26-17" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">12</span>) <span class="sc">+</span></span>
<span id="cb26-18"><a href="análisis-exploratorio-básico.html#cb26-18" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb26-19"><a href="análisis-exploratorio-básico.html#cb26-19" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb26-20"><a href="análisis-exploratorio-básico.html#cb26-20" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;#2c3e50&quot;</span>),</span>
<span id="cb26-21"><a href="análisis-exploratorio-básico.html#cb26-21" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fontface =</span> <span class="st">&quot;bold&quot;</span>)</span>
<span id="cb26-22"><a href="análisis-exploratorio-básico.html#cb26-22" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb26-23"><a href="análisis-exploratorio-básico.html#cb26-23" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Variable, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">scales =</span> <span class="st">&quot;free&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in element_text(color = &quot;white&quot;, fontface = &quot;bold&quot;): `...` must be empty.
## ✖ Problematic argument:
## • fontface = &quot;bold&quot;</code></pre>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/bar_categoricas-1.png" alt="" width="1152" /></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="análisis-exploratorio-básico.html#cb28-1" tabindex="-1"></a>resumen_bivariado_cc <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="análisis-exploratorio-básico.html#cb28-2" tabindex="-1"></a>  <span class="fu">group_by</span>(tipo_equipo) <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="análisis-exploratorio-básico.html#cb28-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb28-4"><a href="análisis-exploratorio-básico.html#cb28-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(costo_transformacion),</span>
<span id="cb28-5"><a href="análisis-exploratorio-básico.html#cb28-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb28-6"><a href="análisis-exploratorio-básico.html#cb28-6" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(costo_transformacion),</span>
<span id="cb28-7"><a href="análisis-exploratorio-básico.html#cb28-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_transformacion),</span>
<span id="cb28-8"><a href="análisis-exploratorio-básico.html#cb28-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(costo_transformacion),</span>
<span id="cb28-9"><a href="análisis-exploratorio-básico.html#cb28-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(costo_transformacion),</span>
<span id="cb28-10"><a href="análisis-exploratorio-básico.html#cb28-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(costo_transformacion, <span class="fl">0.25</span>),</span>
<span id="cb28-11"><a href="análisis-exploratorio-básico.html#cb28-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(costo_transformacion, <span class="fl">0.75</span>),</span>
<span id="cb28-12"><a href="análisis-exploratorio-básico.html#cb28-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(costo_transformacion),</span>
<span id="cb28-13"><a href="análisis-exploratorio-básico.html#cb28-13" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb28-14"><a href="análisis-exploratorio-básico.html#cb28-14" tabindex="-1"></a>  )</span>
<span id="cb28-15"><a href="análisis-exploratorio-básico.html#cb28-15" tabindex="-1"></a></span>
<span id="cb28-16"><a href="análisis-exploratorio-básico.html#cb28-16" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(resumen_bivariado_cc , <span class="at">caption =</span> <span class="st">&quot;Resumen Bivariado costos de transformación&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-17"><a href="análisis-exploratorio-básico.html#cb28-17" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_cc_tipoequipo)(#tab:bivariado_cc_tipoequipo)Resumen Bivariado costos de transformación
</caption>
<thead>
<tr>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
287
</td>
<td style="text-align:right;">
33.033470
</td>
<td style="text-align:right;">
12.711203
</td>
<td style="text-align:right;">
30.382729
</td>
<td style="text-align:right;">
5.093602
</td>
<td style="text-align:right;">
92.17387
</td>
<td style="text-align:right;">
25.312400
</td>
<td style="text-align:right;">
38.34401
</td>
<td style="text-align:right;">
13.031608
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
29.903980
</td>
<td style="text-align:right;">
11.200180
</td>
<td style="text-align:right;">
28.898809
</td>
<td style="text-align:right;">
12.025943
</td>
<td style="text-align:right;">
75.69041
</td>
<td style="text-align:right;">
22.263955
</td>
<td style="text-align:right;">
33.14837
</td>
<td style="text-align:right;">
10.884414
</td>
</tr>
<tr>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
64.358886
</td>
<td style="text-align:right;">
19.163109
</td>
<td style="text-align:right;">
58.779546
</td>
<td style="text-align:right;">
39.674913
</td>
<td style="text-align:right;">
97.18480
</td>
<td style="text-align:right;">
51.829041
</td>
<td style="text-align:right;">
75.60371
</td>
<td style="text-align:right;">
23.774668
</td>
</tr>
<tr>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
8.819827
</td>
<td style="text-align:right;">
3.540393
</td>
<td style="text-align:right;">
8.458577
</td>
<td style="text-align:right;">
2.766110
</td>
<td style="text-align:right;">
21.99044
</td>
<td style="text-align:right;">
6.027059
</td>
<td style="text-align:right;">
10.85749
</td>
<td style="text-align:right;">
4.830435
</td>
</tr>
</tbody>
</table>
<p>El tipo de equipo A1, presenta un costo medio de aproximadamente 33 UM/unidad, con una dispersión moderada. Su mediana cercana a 30 confirma que el comportamiento típico está bien representado y relativamente estable. Esto lo posiciona como el estándar operativo del sistema.</p>
<p>El tipo de equipo B2 muestra un patrón muy similar a A1, aunque con costos ligeramente menores y menor variabilidad. La cercanía entre media y mediana sugiere estabilidad, pero su menor tamaño muestral limita la robustez de la comparación.</p>
<p>El caso de C3 es claramente distinto. Presenta costos significativamente más altos (media superior a 64) y mayor dispersión. Además, el rango intercuartílico es amplio, lo que indica que no solo es costoso, sino también variable. Esto apunta a un proceso con alta complejidad o baja eficiencia estructural.</p>
<p>El tipo de equipo D4 tiene costos notablemente bajos (media cercana a 9). La dispersión es reducida y el comportamiento es consistente. Este equipo representa una operación altamente eficiente y controlada, con baja variabilidad. qué prácticas operativas permiten ese nivel de eficiencia y si son replicables.</p>
<p>El costo de transformación está determinado por el tipo de equipo, y la magnitud de las diferencias es significativa.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="análisis-exploratorio-básico.html#cb29-1" tabindex="-1"></a>resumen_bivariado_ci <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb29-2"><a href="análisis-exploratorio-básico.html#cb29-2" tabindex="-1"></a>  <span class="fu">group_by</span>(tipo_equipo) <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="análisis-exploratorio-básico.html#cb29-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb29-4"><a href="análisis-exploratorio-básico.html#cb29-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(costo_insumo),</span>
<span id="cb29-5"><a href="análisis-exploratorio-básico.html#cb29-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_insumo),</span>
<span id="cb29-6"><a href="análisis-exploratorio-básico.html#cb29-6" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(costo_insumo),</span>
<span id="cb29-7"><a href="análisis-exploratorio-básico.html#cb29-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_insumo),</span>
<span id="cb29-8"><a href="análisis-exploratorio-básico.html#cb29-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(costo_insumo),</span>
<span id="cb29-9"><a href="análisis-exploratorio-básico.html#cb29-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(costo_insumo),</span>
<span id="cb29-10"><a href="análisis-exploratorio-básico.html#cb29-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(costo_insumo, <span class="fl">0.25</span>),</span>
<span id="cb29-11"><a href="análisis-exploratorio-básico.html#cb29-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(costo_insumo, <span class="fl">0.75</span>),</span>
<span id="cb29-12"><a href="análisis-exploratorio-básico.html#cb29-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(costo_insumo),</span>
<span id="cb29-13"><a href="análisis-exploratorio-básico.html#cb29-13" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb29-14"><a href="análisis-exploratorio-básico.html#cb29-14" tabindex="-1"></a>  )</span>
<span id="cb29-15"><a href="análisis-exploratorio-básico.html#cb29-15" tabindex="-1"></a></span>
<span id="cb29-16"><a href="análisis-exploratorio-básico.html#cb29-16" tabindex="-1"></a>    knitr<span class="sc">::</span><span class="fu">kable</span>(resumen_bivariado_ci , <span class="at">caption =</span> <span class="st">&quot;Resumen Bivariado costos de insumo&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-17"><a href="análisis-exploratorio-básico.html#cb29-17" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_ci_tipoequipo)(#tab:bivariado_ci_tipoequipo)Resumen Bivariado costos de insumo
</caption>
<thead>
<tr>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
287
</td>
<td style="text-align:right;">
5.165089
</td>
<td style="text-align:right;">
3.899337
</td>
<td style="text-align:right;">
4.302556
</td>
<td style="text-align:right;">
0.1052334
</td>
<td style="text-align:right;">
36.70551
</td>
<td style="text-align:right;">
2.767850
</td>
<td style="text-align:right;">
6.406926
</td>
<td style="text-align:right;">
3.639076
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
4.993411
</td>
<td style="text-align:right;">
3.259524
</td>
<td style="text-align:right;">
4.513479
</td>
<td style="text-align:right;">
0.5520079
</td>
<td style="text-align:right;">
15.22676
</td>
<td style="text-align:right;">
3.184661
</td>
<td style="text-align:right;">
5.674693
</td>
<td style="text-align:right;">
2.490032
</td>
</tr>
<tr>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
11.255688
</td>
<td style="text-align:right;">
6.102082
</td>
<td style="text-align:right;">
11.410794
</td>
<td style="text-align:right;">
2.4015355
</td>
<td style="text-align:right;">
18.16689
</td>
<td style="text-align:right;">
7.306343
</td>
<td style="text-align:right;">
16.361241
</td>
<td style="text-align:right;">
9.054897
</td>
</tr>
<tr>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
3.582194
</td>
<td style="text-align:right;">
6.364827
</td>
<td style="text-align:right;">
1.643696
</td>
<td style="text-align:right;">
0.0136519
</td>
<td style="text-align:right;">
46.21884
</td>
<td style="text-align:right;">
1.129867
</td>
<td style="text-align:right;">
4.228598
</td>
<td style="text-align:right;">
3.098730
</td>
</tr>
</tbody>
</table>
<p>Los tipos de equipos A1 y B2 presentan patrones similares: medias cercanas a 5 UM/unidad y medianas ligeramente inferiores. El rango intercuartílico es moderado, sugiriendo que el consumo de insumos en estos equipos es predecible y controlado.</p>
<p>El tipo de equipo C3 nuevamente se diferencia de forma clara. La media (≈11.25) es más del doble que en A1 y B2, y la dispersión es considerable. Además, la mediana se mantiene alta. Costoso tanto en transformación como en insumos, es menos eficiente.</p>
<p>El tipo de equipo D4 Presenta la media más baja (≈3.58) pero su desviación estándar es alta y supera incluso a la media. Puede influir que D4 solo opera con un insumo. No puede operar con 2. La mediana (≈1.64) está muy por debajo de la media, lo que indica una asimetría extrema. D4 es generalmente eficiente, pero con episodios puntuales de alto consumo.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="análisis-exploratorio-básico.html#cb30-1" tabindex="-1"></a>box_ct_te <span class="ot">&lt;-</span>datos <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="análisis-exploratorio-básico.html#cb30-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> tipo_equipo, <span class="at">y =</span> costo_transformacion)) <span class="sc">+</span></span>
<span id="cb30-3"><a href="análisis-exploratorio-básico.html#cb30-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#87CEFA&quot;</span>, <span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="análisis-exploratorio-básico.html#cb30-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-5"><a href="análisis-exploratorio-básico.html#cb30-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de equipo&quot;</span>,</span>
<span id="cb30-6"><a href="análisis-exploratorio-básico.html#cb30-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Costo de transformación (UM/unidad)&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-7"><a href="análisis-exploratorio-básico.html#cb30-7" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb30-8"><a href="análisis-exploratorio-básico.html#cb30-8" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Costo de transformación por tipo de equipo&quot;</span>)</span>
<span id="cb30-9"><a href="análisis-exploratorio-básico.html#cb30-9" tabindex="-1"></a></span>
<span id="cb30-10"><a href="análisis-exploratorio-básico.html#cb30-10" tabindex="-1"></a></span>
<span id="cb30-11"><a href="análisis-exploratorio-básico.html#cb30-11" tabindex="-1"></a>box_ci_te <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb30-12"><a href="análisis-exploratorio-básico.html#cb30-12" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> tipo_equipo, <span class="at">y =</span> costo_insumo)) <span class="sc">+</span></span>
<span id="cb30-13"><a href="análisis-exploratorio-básico.html#cb30-13" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#b2df8a&quot;</span>, <span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb30-14"><a href="análisis-exploratorio-básico.html#cb30-14" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;darkgreen&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-15"><a href="análisis-exploratorio-básico.html#cb30-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de equipo&quot;</span>,</span>
<span id="cb30-16"><a href="análisis-exploratorio-básico.html#cb30-16" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Costo de insumo (UM/unidad)&quot;</span>) <span class="sc">+</span></span>
<span id="cb30-17"><a href="análisis-exploratorio-básico.html#cb30-17" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb30-18"><a href="análisis-exploratorio-básico.html#cb30-18" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Costo de insumo por tipo de equipo&quot;</span>)</span>
<span id="cb30-19"><a href="análisis-exploratorio-básico.html#cb30-19" tabindex="-1"></a></span>
<span id="cb30-20"><a href="análisis-exploratorio-básico.html#cb30-20" tabindex="-1"></a>box_ct_te <span class="sc">+</span> box_ci_te </span></code></pre></div>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/box_equipo-1.png" alt="" width="864" /></p>
<p>Los boxplots confirman visualmente lo que ya sugerían los resúmenes numéricos: el tipo de equipo introduce regímenes claramente diferenciados de costos, tanto en transformación como en insumos.</p>
</div>
<div id="análisis-bivariado-equipo_id" class="section level3 hasAnchor" number="2.4.3">
<h3><span class="header-section-number">2.4.3</span> Análisis bivariado: Equipo_id<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-equipo_id" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="análisis-exploratorio-básico.html#cb31-1" tabindex="-1"></a>resumen_bivariado_ct_equipo <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="análisis-exploratorio-básico.html#cb31-2" tabindex="-1"></a>  <span class="fu">group_by</span>(equipo_id, tipo_equipo) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="análisis-exploratorio-básico.html#cb31-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb31-4"><a href="análisis-exploratorio-básico.html#cb31-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(costo_transformacion),</span>
<span id="cb31-5"><a href="análisis-exploratorio-básico.html#cb31-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb31-6"><a href="análisis-exploratorio-básico.html#cb31-6" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(costo_transformacion),</span>
<span id="cb31-7"><a href="análisis-exploratorio-básico.html#cb31-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_transformacion),</span>
<span id="cb31-8"><a href="análisis-exploratorio-básico.html#cb31-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(costo_transformacion),</span>
<span id="cb31-9"><a href="análisis-exploratorio-básico.html#cb31-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(costo_transformacion),</span>
<span id="cb31-10"><a href="análisis-exploratorio-básico.html#cb31-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(costo_transformacion, <span class="fl">0.25</span>),</span>
<span id="cb31-11"><a href="análisis-exploratorio-básico.html#cb31-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(costo_transformacion, <span class="fl">0.75</span>),</span>
<span id="cb31-12"><a href="análisis-exploratorio-básico.html#cb31-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(costo_transformacion),</span>
<span id="cb31-13"><a href="análisis-exploratorio-básico.html#cb31-13" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb31-14"><a href="análisis-exploratorio-básico.html#cb31-14" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb31-15"><a href="análisis-exploratorio-básico.html#cb31-15" tabindex="-1"></a>  <span class="fu">arrange</span>(tipo_equipo, equipo_id)</span>
<span id="cb31-16"><a href="análisis-exploratorio-básico.html#cb31-16" tabindex="-1"></a></span>
<span id="cb31-17"><a href="análisis-exploratorio-básico.html#cb31-17" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb31-18"><a href="análisis-exploratorio-básico.html#cb31-18" tabindex="-1"></a>  resumen_bivariado_ct_equipo,</span>
<span id="cb31-19"><a href="análisis-exploratorio-básico.html#cb31-19" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&quot;Resumen bivariado de costos de transformación por equipo y tipo de equipo&quot;</span></span>
<span id="cb31-20"><a href="análisis-exploratorio-básico.html#cb31-20" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb31-21"><a href="análisis-exploratorio-básico.html#cb31-21" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_cc_quipo)(#tab:bivariado_cc_quipo)Resumen bivariado de costos de transformación por equipo y tipo de equipo
</caption>
<thead>
<tr>
<th style="text-align:left;">
equipo_id
</th>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
M08
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
31.27639
</td>
<td style="text-align:right;">
9.319354
</td>
<td style="text-align:right;">
29.223054
</td>
<td style="text-align:right;">
12.938556
</td>
<td style="text-align:right;">
54.36551
</td>
<td style="text-align:right;">
24.629890
</td>
<td style="text-align:right;">
34.734748
</td>
<td style="text-align:right;">
10.104857
</td>
</tr>
<tr>
<td style="text-align:left;">
M09
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
33.34972
</td>
<td style="text-align:right;">
15.921560
</td>
<td style="text-align:right;">
28.943841
</td>
<td style="text-align:right;">
7.458185
</td>
<td style="text-align:right;">
92.17387
</td>
<td style="text-align:right;">
24.663711
</td>
<td style="text-align:right;">
38.417845
</td>
<td style="text-align:right;">
13.754134
</td>
</tr>
<tr>
<td style="text-align:left;">
M13
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
30.30618
</td>
<td style="text-align:right;">
9.351186
</td>
<td style="text-align:right;">
28.920109
</td>
<td style="text-align:right;">
14.168156
</td>
<td style="text-align:right;">
53.04372
</td>
<td style="text-align:right;">
23.778610
</td>
<td style="text-align:right;">
34.135578
</td>
<td style="text-align:right;">
10.356968
</td>
</tr>
<tr>
<td style="text-align:left;">
M14
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
33.51819
</td>
<td style="text-align:right;">
11.898987
</td>
<td style="text-align:right;">
31.803886
</td>
<td style="text-align:right;">
18.285332
</td>
<td style="text-align:right;">
76.49633
</td>
<td style="text-align:right;">
24.591653
</td>
<td style="text-align:right;">
38.140008
</td>
<td style="text-align:right;">
13.548355
</td>
</tr>
<tr>
<td style="text-align:left;">
M15
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
38.01583
</td>
<td style="text-align:right;">
11.775535
</td>
<td style="text-align:right;">
35.608155
</td>
<td style="text-align:right;">
8.470757
</td>
<td style="text-align:right;">
73.82103
</td>
<td style="text-align:right;">
30.007093
</td>
<td style="text-align:right;">
44.145193
</td>
<td style="text-align:right;">
14.138099
</td>
</tr>
<tr>
<td style="text-align:left;">
M16
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
33.68989
</td>
<td style="text-align:right;">
15.958812
</td>
<td style="text-align:right;">
29.570643
</td>
<td style="text-align:right;">
5.093602
</td>
<td style="text-align:right;">
91.71969
</td>
<td style="text-align:right;">
25.502138
</td>
<td style="text-align:right;">
41.333351
</td>
<td style="text-align:right;">
15.831213
</td>
</tr>
<tr>
<td style="text-align:left;">
M17
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
30.36666
</td>
<td style="text-align:right;">
11.049502
</td>
<td style="text-align:right;">
30.077145
</td>
<td style="text-align:right;">
8.756984
</td>
<td style="text-align:right;">
80.57443
</td>
<td style="text-align:right;">
24.208872
</td>
<td style="text-align:right;">
33.989632
</td>
<td style="text-align:right;">
9.780761
</td>
</tr>
<tr>
<td style="text-align:left;">
M02
</td>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
29.90398
</td>
<td style="text-align:right;">
11.200180
</td>
<td style="text-align:right;">
28.898809
</td>
<td style="text-align:right;">
12.025943
</td>
<td style="text-align:right;">
75.69041
</td>
<td style="text-align:right;">
22.263955
</td>
<td style="text-align:right;">
33.148368
</td>
<td style="text-align:right;">
10.884414
</td>
</tr>
<tr>
<td style="text-align:left;">
M04
</td>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
79.35268
</td>
<td style="text-align:right;">
14.636401
</td>
<td style="text-align:right;">
78.463097
</td>
<td style="text-align:right;">
63.299747
</td>
<td style="text-align:right;">
97.18480
</td>
<td style="text-align:right;">
70.383177
</td>
<td style="text-align:right;">
87.432605
</td>
<td style="text-align:right;">
17.049427
</td>
</tr>
<tr>
<td style="text-align:left;">
M11
</td>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
49.36509
</td>
<td style="text-align:right;">
6.567305
</td>
<td style="text-align:right;">
51.763046
</td>
<td style="text-align:right;">
39.674913
</td>
<td style="text-align:right;">
54.25934
</td>
<td style="text-align:right;">
48.642021
</td>
<td style="text-align:right;">
52.486113
</td>
<td style="text-align:right;">
3.844092
</td>
</tr>
<tr>
<td style="text-align:left;">
M05
</td>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
10.10229
</td>
<td style="text-align:right;">
3.754173
</td>
<td style="text-align:right;">
9.992373
</td>
<td style="text-align:right;">
4.682246
</td>
<td style="text-align:right;">
21.99044
</td>
<td style="text-align:right;">
7.603790
</td>
<td style="text-align:right;">
11.950964
</td>
<td style="text-align:right;">
4.347174
</td>
</tr>
<tr>
<td style="text-align:left;">
M12
</td>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
7.16331
</td>
<td style="text-align:right;">
2.442369
</td>
<td style="text-align:right;">
6.383549
</td>
<td style="text-align:right;">
2.766110
</td>
<td style="text-align:right;">
11.54071
</td>
<td style="text-align:right;">
5.354565
</td>
<td style="text-align:right;">
8.584072
</td>
<td style="text-align:right;">
3.229508
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="análisis-exploratorio-básico.html#cb32-1" tabindex="-1"></a>resumen_bivariado_ci_equipo <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="análisis-exploratorio-básico.html#cb32-2" tabindex="-1"></a>  <span class="fu">group_by</span>(equipo_id, tipo_equipo) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="análisis-exploratorio-básico.html#cb32-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb32-4"><a href="análisis-exploratorio-básico.html#cb32-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(costo_insumo),</span>
<span id="cb32-5"><a href="análisis-exploratorio-básico.html#cb32-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_insumo),</span>
<span id="cb32-6"><a href="análisis-exploratorio-básico.html#cb32-6" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(costo_insumo),</span>
<span id="cb32-7"><a href="análisis-exploratorio-básico.html#cb32-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_insumo),</span>
<span id="cb32-8"><a href="análisis-exploratorio-básico.html#cb32-8" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(costo_insumo),</span>
<span id="cb32-9"><a href="análisis-exploratorio-básico.html#cb32-9" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(costo_insumo),</span>
<span id="cb32-10"><a href="análisis-exploratorio-básico.html#cb32-10" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(costo_insumo, <span class="fl">0.25</span>),</span>
<span id="cb32-11"><a href="análisis-exploratorio-básico.html#cb32-11" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(costo_insumo, <span class="fl">0.75</span>),</span>
<span id="cb32-12"><a href="análisis-exploratorio-básico.html#cb32-12" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(costo_insumo),</span>
<span id="cb32-13"><a href="análisis-exploratorio-básico.html#cb32-13" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb32-14"><a href="análisis-exploratorio-básico.html#cb32-14" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-15"><a href="análisis-exploratorio-básico.html#cb32-15" tabindex="-1"></a>  <span class="fu">arrange</span>(tipo_equipo, equipo_id)</span>
<span id="cb32-16"><a href="análisis-exploratorio-básico.html#cb32-16" tabindex="-1"></a></span>
<span id="cb32-17"><a href="análisis-exploratorio-básico.html#cb32-17" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb32-18"><a href="análisis-exploratorio-básico.html#cb32-18" tabindex="-1"></a>  resumen_bivariado_ci_equipo,</span>
<span id="cb32-19"><a href="análisis-exploratorio-básico.html#cb32-19" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">&quot;Resumen bivariado de costos de insumo por equipo y tipo de equipo&quot;</span></span>
<span id="cb32-20"><a href="análisis-exploratorio-básico.html#cb32-20" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb32-21"><a href="análisis-exploratorio-básico.html#cb32-21" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_ci_equipo)(#tab:bivariado_ci_equipo)Resumen bivariado de costos de insumo por equipo y tipo de equipo
</caption>
<thead>
<tr>
<th style="text-align:left;">
equipo_id
</th>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:right;">
n
</th>
<th style="text-align:right;">
media
</th>
<th style="text-align:right;">
ds
</th>
<th style="text-align:right;">
50%
</th>
<th style="text-align:right;">
minimo
</th>
<th style="text-align:right;">
maximo
</th>
<th style="text-align:right;">
Q1
</th>
<th style="text-align:right;">
Q3
</th>
<th style="text-align:right;">
IQR
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
M08
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
5.665050
</td>
<td style="text-align:right;">
4.0368197
</td>
<td style="text-align:right;">
3.992955
</td>
<td style="text-align:right;">
0.1295180
</td>
<td style="text-align:right;">
15.886596
</td>
<td style="text-align:right;">
2.8173810
</td>
<td style="text-align:right;">
7.325198
</td>
<td style="text-align:right;">
4.5078168
</td>
</tr>
<tr>
<td style="text-align:left;">
M09
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
5.509164
</td>
<td style="text-align:right;">
3.2870116
</td>
<td style="text-align:right;">
4.221224
</td>
<td style="text-align:right;">
1.1656617
</td>
<td style="text-align:right;">
17.180955
</td>
<td style="text-align:right;">
3.2953136
</td>
<td style="text-align:right;">
7.055640
</td>
<td style="text-align:right;">
3.7603260
</td>
</tr>
<tr>
<td style="text-align:left;">
M13
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
3.913840
</td>
<td style="text-align:right;">
2.0886719
</td>
<td style="text-align:right;">
3.827828
</td>
<td style="text-align:right;">
0.1148000
</td>
<td style="text-align:right;">
7.777352
</td>
<td style="text-align:right;">
2.5527477
</td>
<td style="text-align:right;">
5.727522
</td>
<td style="text-align:right;">
3.1747739
</td>
</tr>
<tr>
<td style="text-align:left;">
M14
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
5.435045
</td>
<td style="text-align:right;">
3.1086539
</td>
<td style="text-align:right;">
4.936789
</td>
<td style="text-align:right;">
0.2104667
</td>
<td style="text-align:right;">
17.516200
</td>
<td style="text-align:right;">
3.7962138
</td>
<td style="text-align:right;">
6.162844
</td>
<td style="text-align:right;">
2.3666304
</td>
</tr>
<tr>
<td style="text-align:left;">
M15
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
5.506860
</td>
<td style="text-align:right;">
4.1066146
</td>
<td style="text-align:right;">
4.487847
</td>
<td style="text-align:right;">
0.1052334
</td>
<td style="text-align:right;">
21.803883
</td>
<td style="text-align:right;">
3.2820200
</td>
<td style="text-align:right;">
6.588681
</td>
<td style="text-align:right;">
3.3066613
</td>
</tr>
<tr>
<td style="text-align:left;">
M16
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
5.238026
</td>
<td style="text-align:right;">
3.6697466
</td>
<td style="text-align:right;">
4.404447
</td>
<td style="text-align:right;">
0.2296000
</td>
<td style="text-align:right;">
17.602453
</td>
<td style="text-align:right;">
2.6865152
</td>
<td style="text-align:right;">
6.088540
</td>
<td style="text-align:right;">
3.4020245
</td>
</tr>
<tr>
<td style="text-align:left;">
M17
</td>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
4.823398
</td>
<td style="text-align:right;">
5.7074695
</td>
<td style="text-align:right;">
2.830810
</td>
<td style="text-align:right;">
0.8796594
</td>
<td style="text-align:right;">
36.705510
</td>
<td style="text-align:right;">
1.8922415
</td>
<td style="text-align:right;">
5.478526
</td>
<td style="text-align:right;">
3.5862843
</td>
</tr>
<tr>
<td style="text-align:left;">
M02
</td>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
4.993411
</td>
<td style="text-align:right;">
3.2595239
</td>
<td style="text-align:right;">
4.513479
</td>
<td style="text-align:right;">
0.5520079
</td>
<td style="text-align:right;">
15.226761
</td>
<td style="text-align:right;">
3.1846611
</td>
<td style="text-align:right;">
5.674693
</td>
<td style="text-align:right;">
2.4900316
</td>
</tr>
<tr>
<td style="text-align:left;">
M04
</td>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
13.836663
</td>
<td style="text-align:right;">
6.2070796
</td>
<td style="text-align:right;">
16.162889
</td>
<td style="text-align:right;">
4.8539876
</td>
<td style="text-align:right;">
18.166888
</td>
<td style="text-align:right;">
12.1122718
</td>
<td style="text-align:right;">
17.887280
</td>
<td style="text-align:right;">
5.7750083
</td>
</tr>
<tr>
<td style="text-align:left;">
M11
</td>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
8.674712
</td>
<td style="text-align:right;">
5.5309078
</td>
<td style="text-align:right;">
8.206842
</td>
<td style="text-align:right;">
2.4015355
</td>
<td style="text-align:right;">
15.883629
</td>
<td style="text-align:right;">
6.6932305
</td>
<td style="text-align:right;">
10.188323
</td>
<td style="text-align:right;">
3.4950925
</td>
</tr>
<tr>
<td style="text-align:left;">
M05
</td>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
5.277321
</td>
<td style="text-align:right;">
8.0884424
</td>
<td style="text-align:right;">
3.527777
</td>
<td style="text-align:right;">
0.5267213
</td>
<td style="text-align:right;">
46.218837
</td>
<td style="text-align:right;">
1.4020887
</td>
<td style="text-align:right;">
5.848744
</td>
<td style="text-align:right;">
4.4466553
</td>
</tr>
<tr>
<td style="text-align:left;">
M12
</td>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
1.392655
</td>
<td style="text-align:right;">
0.9503512
</td>
<td style="text-align:right;">
1.246863
</td>
<td style="text-align:right;">
0.0136519
</td>
<td style="text-align:right;">
3.608001
</td>
<td style="text-align:right;">
0.9263307
</td>
<td style="text-align:right;">
1.635555
</td>
<td style="text-align:right;">
0.7092244
</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="análisis-exploratorio-básico.html#cb33-1" tabindex="-1"></a>orden_equipos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="análisis-exploratorio-básico.html#cb33-2" tabindex="-1"></a>  <span class="fu">distinct</span>(tipo_equipo, equipo_id) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="análisis-exploratorio-básico.html#cb33-3" tabindex="-1"></a>  <span class="fu">arrange</span>(tipo_equipo, equipo_id) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="análisis-exploratorio-básico.html#cb33-4" tabindex="-1"></a>  <span class="fu">pull</span>(equipo_id)</span>
<span id="cb33-5"><a href="análisis-exploratorio-básico.html#cb33-5" tabindex="-1"></a></span>
<span id="cb33-6"><a href="análisis-exploratorio-básico.html#cb33-6" tabindex="-1"></a>  box_ct_equipo <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb33-7"><a href="análisis-exploratorio-básico.html#cb33-7" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-8"><a href="análisis-exploratorio-básico.html#cb33-8" tabindex="-1"></a>    <span class="at">equipo_id =</span> <span class="fu">factor</span>(equipo_id, <span class="at">levels =</span> orden_equipos)</span>
<span id="cb33-9"><a href="análisis-exploratorio-básico.html#cb33-9" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb33-10"><a href="análisis-exploratorio-básico.html#cb33-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> equipo_id, <span class="at">y =</span> costo_transformacion, <span class="at">fill =</span> tipo_equipo)) <span class="sc">+</span></span>
<span id="cb33-11"><a href="análisis-exploratorio-básico.html#cb33-11" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb33-12"><a href="análisis-exploratorio-básico.html#cb33-12" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-13"><a href="análisis-exploratorio-básico.html#cb33-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Equipo&quot;</span>,</span>
<span id="cb33-14"><a href="análisis-exploratorio-básico.html#cb33-14" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Costo de transformación (UM/unidad)&quot;</span>,</span>
<span id="cb33-15"><a href="análisis-exploratorio-básico.html#cb33-15" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Tipo de equipo&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-16"><a href="análisis-exploratorio-básico.html#cb33-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb33-17"><a href="análisis-exploratorio-básico.html#cb33-17" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb33-18"><a href="análisis-exploratorio-básico.html#cb33-18" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Costo de transformación por equipo&quot;</span>)</span>
<span id="cb33-19"><a href="análisis-exploratorio-básico.html#cb33-19" tabindex="-1"></a></span>
<span id="cb33-20"><a href="análisis-exploratorio-básico.html#cb33-20" tabindex="-1"></a>box_ci_equipo <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb33-21"><a href="análisis-exploratorio-básico.html#cb33-21" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb33-22"><a href="análisis-exploratorio-básico.html#cb33-22" tabindex="-1"></a>    <span class="at">equipo_id =</span> <span class="fu">factor</span>(equipo_id, <span class="at">levels =</span> orden_equipos)</span>
<span id="cb33-23"><a href="análisis-exploratorio-básico.html#cb33-23" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb33-24"><a href="análisis-exploratorio-básico.html#cb33-24" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> equipo_id, <span class="at">y =</span> costo_insumo, <span class="at">fill =</span> tipo_equipo)) <span class="sc">+</span></span>
<span id="cb33-25"><a href="análisis-exploratorio-básico.html#cb33-25" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb33-26"><a href="análisis-exploratorio-básico.html#cb33-26" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-27"><a href="análisis-exploratorio-básico.html#cb33-27" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Equipo&quot;</span>,</span>
<span id="cb33-28"><a href="análisis-exploratorio-básico.html#cb33-28" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Costo de insumo (UM/unidad)&quot;</span>,</span>
<span id="cb33-29"><a href="análisis-exploratorio-básico.html#cb33-29" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">&quot;Tipo de equipo&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-30"><a href="análisis-exploratorio-básico.html#cb33-30" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb33-31"><a href="análisis-exploratorio-básico.html#cb33-31" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb33-32"><a href="análisis-exploratorio-básico.html#cb33-32" tabindex="-1"></a>  <span class="fu">facet_grid</span>(. <span class="sc">~</span> <span class="st">&quot;Costo de insumo por equipo&quot;</span>)</span>
<span id="cb33-33"><a href="análisis-exploratorio-básico.html#cb33-33" tabindex="-1"></a></span>
<span id="cb33-34"><a href="análisis-exploratorio-básico.html#cb33-34" tabindex="-1"></a>box_ct_equipo <span class="sc">+</span> box_ci_equipo</span></code></pre></div>
<p><img src="libro-maestria-estadistica-aplicada_files/figure-html/box_equipoid-1.png" alt="" width="864" /></p>
<p>A1 (M08, M09, M13, M14, M15, M16, M17): siete equipos con costo de transformación medio entre 30 y 38 UM/unidad. La variabilidad intra-equipo es alta, pero la variabilidad entre equipos del mismo tipo es modesta. Los siete equipos se comportan como una familia coherente.
B2 (M02): un único equipo. Su perfil es indistinguible visualmente de los equipos A1. Esto plantea una pregunta operativa relevante: si M02 (B2) opera con costos similares a los siete equipos A1, ¿qué justifica mantener una clasificación tecnológica separada?
C3 (M04, M11): dos equipos con costos significativamente más altos que el resto, pero muy diferentes entre sí. M04 opera en torno a 79 UM/unidad, M11 en torno a 49 UM/unidad. Tratarlos como un solo grupo “C3” oscurece esta diferencia.
D4 (M05, M12): dos equipos con costos significativamente más bajos que el resto, también diferentes entre sí. M05 promedia 10 UM/unidad, M12 promedia 7 UM/unidad. La diferencia es proporcionalmente importante.</p>
<p>Interpretación por tipo
- A1: Los siete equipos muestran un comportamiento notablemente similar, tanto en costo de transformación como en costo de insumo. Las medias se mueven entre 30 y 38 UM/unidad, los IQR son comparables (10–16 UM), y los outliers superiores aparecen distribuidos de forma similar. M15 destaca ligeramente como el más costoso del grupo (media 38, mediana 35.6), mientras que M13 y M17 son los más bajos. Pero ninguna de estas diferencias es lo suficientemente grande para considerar que los equipos operan en regímenes distintos.
aunque la media de M15 es la más alta del grupo, su IQR (14.1) no es el más amplio y su distribución no muestra patología visible. El hecho de que M15 promedie ~5 UM/unidad más que M13 podría ser estructural (productos asignados sistemáticamente más complejos) o aleatorio (mezcla particular de órdenes en el período). El EDA no permite distinguir entre las dos hipótesis; un análisis estratificado por categoría_producto sería el siguiente paso.
- B2: toda conclusión sobre el “tipo B2” es en realidad una conclusión sobre el equipo M02 específico. Visualmente, M02 es indistinguible del cluster A1: media 29.9, mediana 28.9, IQR 10.9, todos en el rango de los equipos A1.</p>
<p>B2 y A1 son tecnologías similares en costo, y mantenerlas como categorías separadas refleja diferencias técnicas (tamaño, año, fabricante) que no se traducen en costo unitario observable.
<strong>qué diferencia formalmente a B2 de A1 y si esa diferencia debe seguir siendo una dimensión de análisis.</strong></p>
<ul>
<li>C3 es donde la subdivisión por equipo individual cambia más radicalmente . M04 (n=4) opera con un costo de transformación medio de 79.4 UM/unidad; M11 (n=4) opera con 49.4. La diferencia entre estos dos equipos (30 UM/unidad) es mayor que la diferencia entre A1 y D4 (que es de unas 25 UM). Tratarlos como un grupo “C3” da un promedio de 64.4, que no representa adecuadamente ni a M04 ni a M11.
las distribuciones intra-equipo son distintas: M11 tiene un IQR de 3.8 (muy estable dentro de su nivel), mientras que M04 tiene un IQR de 17.0 (alta variabilidad). M04 no solo es más caro: también es menos predecible.</li>
<li>D4: M05 y M12 son ambos significativamente más eficientes que el resto del sistema, pero también son distintos entre sí: M05 promedia 10.1 UM/unidad, M12 promedia 7.2. La diferencia absoluta (3 UM/unidad) parece pequeña en el contexto del sistema, pero representa una diferencia relativa del 40% entre ambos equipos.
En costo de insumo, la diferencia es aún más marcada: M05 con media 5.3, M12 con media 1.4. Sin embargo, M05 muestra una desviación estándar de 8.1 con un máximo de 46.2, lo que indica al menos un outlier extremo. Esto compromete la lectura de M05 — su comportamiento “típico” puede ser muy distinto del que sugiere su media.
<strong>¿qué hace que M12 sea más eficiente que M05? Si es una diferencia estructural (ejemplo: M12 procesa productos más simples), entonces la diferencia es una composición. Si es una diferencia técnica del equipo (mejor mantenimiento, operario más capacitado, tecnología más nueva), entonces hay una oportunidad de mejora replicable hacia M05.</strong></li>
</ul>
<p>En conclusión , el análisis por tipo de equipo muestra diferencias muy grandes:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="análisis-exploratorio-básico.html#cb34-1" tabindex="-1"></a>tabla_resumen <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="análisis-exploratorio-básico.html#cb34-2" tabindex="-1"></a>  <span class="fu">group_by</span>(tipo_equipo) <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="análisis-exploratorio-básico.html#cb34-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb34-4"><a href="análisis-exploratorio-básico.html#cb34-4" tabindex="-1"></a>    <span class="at">costo_transformacion_medio =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb34-5"><a href="análisis-exploratorio-básico.html#cb34-5" tabindex="-1"></a>    <span class="at">costo_insumo_medio =</span> <span class="fu">mean</span>(costo_insumo),</span>
<span id="cb34-6"><a href="análisis-exploratorio-básico.html#cb34-6" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb34-7"><a href="análisis-exploratorio-básico.html#cb34-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb34-8"><a href="análisis-exploratorio-básico.html#cb34-8" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb34-9"><a href="análisis-exploratorio-básico.html#cb34-9" tabindex="-1"></a>    <span class="at">costo_transformacion_medio =</span> <span class="fu">round</span>(costo_transformacion_medio, <span class="dv">1</span>),</span>
<span id="cb34-10"><a href="análisis-exploratorio-básico.html#cb34-10" tabindex="-1"></a>    <span class="at">costo_insumo_medio =</span> <span class="fu">round</span>(costo_insumo_medio, <span class="dv">1</span>)</span>
<span id="cb34-11"><a href="análisis-exploratorio-básico.html#cb34-11" tabindex="-1"></a>  )</span>
<span id="cb34-12"><a href="análisis-exploratorio-básico.html#cb34-12" tabindex="-1"></a></span>
<span id="cb34-13"><a href="análisis-exploratorio-básico.html#cb34-13" tabindex="-1"></a><span class="fu">kable</span>(tabla_resumen, <span class="at">caption =</span> <span class="st">&quot;Tabla resumen costos por tipo de equipo&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-14"><a href="análisis-exploratorio-básico.html#cb34-14" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:res_cost_tipoequipo)(#tab:res_cost_tipoequipo)Tabla resumen costos por tipo de equipo
</caption>
<thead>
<tr>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:right;">
costo_transformacion_medio
</th>
<th style="text-align:right;">
costo_insumo_medio
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
33.0
</td>
<td style="text-align:right;">
5.2
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
29.9
</td>
<td style="text-align:right;">
5.0
</td>
</tr>
<tr>
<td style="text-align:left;">
C3
</td>
<td style="text-align:right;">
64.4
</td>
<td style="text-align:right;">
11.3
</td>
</tr>
<tr>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
8.8
</td>
<td style="text-align:right;">
3.6
</td>
</tr>
</tbody>
</table>
<p>Las diferencias son tan marcadas que invitan a preguntar: ¿cada tipo de equipo es realmente comparable con los otros?
Una tabulación cruzada contesta la pregunta y cambia el análisis:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="análisis-exploratorio-básico.html#cb35-1" tabindex="-1"></a>tabla_dep <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="análisis-exploratorio-básico.html#cb35-2" tabindex="-1"></a>  <span class="fu">count</span>(tipo_equipo, modalidad_proceso, num_insumos) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="análisis-exploratorio-básico.html#cb35-3" tabindex="-1"></a>  <span class="fu">complete</span>(tipo_equipo, modalidad_proceso, num_insumos, <span class="at">fill =</span> <span class="fu">list</span>(<span class="at">n =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb35-4"><a href="análisis-exploratorio-básico.html#cb35-4" tabindex="-1"></a>  <span class="fu">arrange</span>(tipo_equipo, modalidad_proceso, num_insumos)</span>
<span id="cb35-5"><a href="análisis-exploratorio-básico.html#cb35-5" tabindex="-1"></a></span>
<span id="cb35-6"><a href="análisis-exploratorio-básico.html#cb35-6" tabindex="-1"></a>filas_vacias <span class="ot">&lt;-</span> <span class="fu">which</span>(tabla_dep<span class="sc">$</span>n <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb35-7"><a href="análisis-exploratorio-básico.html#cb35-7" tabindex="-1"></a></span>
<span id="cb35-8"><a href="análisis-exploratorio-básico.html#cb35-8" tabindex="-1"></a><span class="fu">kable</span>(tabla_dep, <span class="at">caption =</span> <span class="st">&quot;Combinaciones observadas con resaltado en ceros&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb35-9"><a href="análisis-exploratorio-básico.html#cb35-9" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">&quot;striped&quot;</span>, <span class="st">&quot;hover&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb35-10"><a href="análisis-exploratorio-básico.html#cb35-10" tabindex="-1"></a>  <span class="fu">row_spec</span>(filas_vacias, <span class="at">bold =</span> <span class="cn">TRUE</span>, <span class="at">background =</span> <span class="st">&quot;#FFE6E6&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#D32F2F&quot;</span>) <span class="co"># Rojo claro para resaltar</span></span></code></pre></div>
<table class="table table-striped table-hover" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:bivariado_cost_tipoequipo)(#tab:bivariado_cost_tipoequipo)Combinaciones observadas con resaltado en ceros
</caption>
<thead>
<tr>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:left;">
modalidad_proceso
</th>
<th style="text-align:left;">
num_insumos
</th>
<th style="text-align:right;">
n
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
60
</td>
</tr>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
63
</td>
</tr>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
118
</td>
</tr>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:left;">
Z
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:left;">
Z
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
18
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:left;">
Y
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:left;">
Z
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
B2
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Z
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
C3
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
7
</td>
</tr>
<tr>
<td style="text-align:left;">
C3
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
2
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
C3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Y
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
C3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Y
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
C3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Z
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
C3
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Z
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
D4
</td>
<td style="text-align:left;">
X
</td>
<td style="text-align:left;">
1
</td>
<td style="text-align:right;">
55
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
D4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
X
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
D4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Y
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
D4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Y
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
D4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Z
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
1
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
D4
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
Z
</td>
<td style="text-align:left;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
2
</td>
<td style="text-align:right;font-weight: bold;color: rgba(211, 47, 47, 255) !important;background-color: rgba(255, 230, 230, 255) !important;">
0
</td>
</tr>
</tbody>
</table>
<p>El espacio operativo no es completo. No todos los equipos operan en todas las modalidades. No todas las modalidades se ejecutan con todos los números de insumos. Las combinaciones son asimétricas y muchas celdas están vacías o con muy pocas observaciones.</p>
<p><strong>Lo que parecía un dataset plano co variables categóricas independientes es en realidad un sistema con dependencias operativas:</strong>
- El tipo de equipo determina qué modalidades de proceso son factibles.
- El tipo de equipo determina el número de insumos.</p>
<p>El dataset refleja restricciones técnicas reales de la planta, no una muestra aleatoria de un universo uniforme.</p>
<p>Si las categorías no son independientes, comparar costos marginalmente es engañoso. Ejemplo concreto:</p>
<p>Si D4 solo opera en modalidad X con 1 insumo, y A1 opera en X, Y y Z con 1 o 2 insumos, entonces decir “D4 es más barato que A1” mezcla dos cosas: el efecto del equipo y el efecto de la modalidad/insumos. No sabemos si D4 es barato porque el equipo es eficiente, o porque solo se usa en las configuraciones más simples.</p>
<p>Este tipo de error se llama confusión (confounding) y es una de las trampas clásicas de los análisis agregados.</p>
<p>Desde este punto del capítulo, el análisis abandona la lógica “promedio por categoría” y adopta una lógica condicional: cada efecto se evalúa dentro del contexto operativo donde sí hay comparabilidad.</p>
</div>
</div>
<div id="decisiones-metodológicas-derivadas-del-eda-inicial" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Decisiones metodológicas derivadas del EDA inicial<a href="análisis-exploratorio-básico.html#decisiones-metodol%C3%B3gicas-derivadas-del-eda-inicial" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Tras el diagnóstico anterior, se adoptan tres decisiones que guían el resto del capítulo:
Decisión 1 — Exclusión de modalidad Z. La modalidad Z corresponde a órdenes excepcionales donde se aplican las modalidades X y Y al mismo producto por solicitud del cliente. Con 14 órdenes distribuidas en 3 celdas (3.5% del dataset), no permite inferencia estadística con potencia suficiente y, al representar una composición de procesos en lugar de una modalidad alternativa, no es conceptualmente comparable con X o Y. Las órdenes con Z se excluyen del análisis principal y se caracterizan brevemente al final del capítulo (sección 6.8).
Decisión 2 — Exclusión del tipo_equipo C3. C3 tiene solo 8 órdenes (2%), concentradas casi íntegramente en la combinación (X, 1) con un único caso en (X, 2) y cero en modalidad Y. Con este n, los intervalos de confianza son extremadamente amplios y cualquier diferencia observada queda dominada por ruido. C3 se excluye del análisis estratificado y sus estadísticos descriptivos se reportan al final con una advertencia explícita sobre su no comparabilidad.
Decisión 3 — Configuración universal. Tras excluir Z y C3, el equipo A1 es el único que cubre las 4 combinaciones (X × Y × 1 × 2), con 274 órdenes. Es la única base analítica donde es posible evaluar de forma limpia los efectos de modalidad y número de insumos. Los análisis multivariados profundos se desarrollarán sobre este subconjunto.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="análisis-exploratorio-básico.html#cb36-1" tabindex="-1"></a>datos_principal <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="análisis-exploratorio-básico.html#cb36-2" tabindex="-1"></a>  <span class="fu">filter</span>(modalidad_proceso <span class="sc">!=</span> <span class="st">&quot;Z&quot;</span>,</span>
<span id="cb36-3"><a href="análisis-exploratorio-básico.html#cb36-3" tabindex="-1"></a>         tipo_equipo <span class="sc">!=</span> <span class="st">&quot;C3&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb36-4"><a href="análisis-exploratorio-básico.html#cb36-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">modalidad_proceso =</span> <span class="fu">droplevels</span>(modalidad_proceso),</span>
<span id="cb36-5"><a href="análisis-exploratorio-básico.html#cb36-5" tabindex="-1"></a>         <span class="at">tipo_equipo       =</span> <span class="fu">droplevels</span>(tipo_equipo))</span>
<span id="cb36-6"><a href="análisis-exploratorio-básico.html#cb36-6" tabindex="-1"></a></span>
<span id="cb36-7"><a href="análisis-exploratorio-básico.html#cb36-7" tabindex="-1"></a><span class="fu">write_csv2</span>(datos_principal, <span class="st">&quot;data/data_costos_principal.csv&quot;</span>)</span>
<span id="cb36-8"><a href="análisis-exploratorio-básico.html#cb36-8" tabindex="-1"></a><span class="fu">saveRDS</span>(datos_principal, <span class="st">&quot;data/data_costos_principal.rds&quot;</span>)</span>
<span id="cb36-9"><a href="análisis-exploratorio-básico.html#cb36-9" tabindex="-1"></a></span>
<span id="cb36-10"><a href="análisis-exploratorio-básico.html#cb36-10" tabindex="-1"></a>n_principal <span class="ot">&lt;-</span> <span class="fu">nrow</span>(datos_principal)</span></code></pre></div>
<p>Tras estas exclusiones, el dataset principal queda conformado por r n_principal órdenes . Sobre este subconjunto se desarrolla el análisis estratificado que sigue.</p>
</div>
<div id="estructura-del-espacio-operativo-sobre-el-dataset-principal" class="section level2 hasAnchor" number="2.6">
<h2><span class="header-section-number">2.6</span> Estructura del espacio operativo sobre el dataset principal<a href="análisis-exploratorio-básico.html#estructura-del-espacio-operativo-sobre-el-dataset-principal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="mapa-de-combinaciones" class="section level3 hasAnchor" number="2.6.1">
<h3><span class="header-section-number">2.6.1</span> Mapa de combinaciones<a href="análisis-exploratorio-básico.html#mapa-de-combinaciones" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="análisis-exploratorio-básico.html#cb37-1" tabindex="-1"></a>mapa_n <span class="ot">&lt;-</span> datos_principal <span class="sc">%&gt;%</span></span>
<span id="cb37-2"><a href="análisis-exploratorio-básico.html#cb37-2" tabindex="-1"></a>  <span class="fu">count</span>(tipo_equipo, modalidad_proceso, num_insumos) <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="análisis-exploratorio-básico.html#cb37-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> <span class="fu">c</span>(modalidad_proceso, num_insumos),</span>
<span id="cb37-4"><a href="análisis-exploratorio-básico.html#cb37-4" tabindex="-1"></a>              <span class="at">values_from =</span> n,</span>
<span id="cb37-5"><a href="análisis-exploratorio-básico.html#cb37-5" tabindex="-1"></a>              <span class="at">values_fill =</span> <span class="dv">0</span>,</span>
<span id="cb37-6"><a href="análisis-exploratorio-básico.html#cb37-6" tabindex="-1"></a>              <span class="at">names_sep =</span> <span class="st">&quot;_&quot;</span>)</span>
<span id="cb37-7"><a href="análisis-exploratorio-básico.html#cb37-7" tabindex="-1"></a></span>
<span id="cb37-8"><a href="análisis-exploratorio-básico.html#cb37-8" tabindex="-1"></a><span class="fu">kable</span>(mapa_n, <span class="at">caption =</span> <span class="st">&quot;Tamaño muestral por combinación (dataset principal)&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb37-9"><a href="análisis-exploratorio-básico.html#cb37-9" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
(#tab:mapa_combinaciones)(#tab:mapa_combinaciones)Tamaño muestral por combinación (dataset principal)
</caption>
<thead>
<tr>
<th style="text-align:left;">
tipo_equipo
</th>
<th style="text-align:right;">
X_1
</th>
<th style="text-align:right;">
X_2
</th>
<th style="text-align:right;">
Y_1
</th>
<th style="text-align:right;">
Y_2
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
A1
</td>
<td style="text-align:right;">
60
</td>
<td style="text-align:right;">
63
</td>
<td style="text-align:right;">
118
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
B2
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
D4
</td>
<td style="text-align:right;">
55
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>A1 tiene cobertura completa: 60 órdenes en (X, 1), 63 en (X, 2), 118 en (Y, 1), 33 en (Y, 2). Total: 274. Es el único equipo que permite comparar simultáneamente los efectos de modalidad y de número de insumos.
B2 tiene cobertura en las 4 combinaciones pero con n reducido (7, 13, 18, 6). Permite análisis condicional con cautela.
D4 opera exclusivamente en (X, 1) con 55 órdenes. No se puede estudiar si D4 cambia de comportamiento en otras modalidades o con otros insumos: esa información no existe.</p>
<p>Este mapa define el universo de comparaciones legítimas:</p>
<p>Comparación inter-equipos en (X, 1): es el único estrato donde A1 (n=60), B2 (n=7) y D4 (n=55) coexisten. Total: 122 órdenes. Es la única celda limpia para responder la pregunta “¿los equipos difieren en costo?”.
Comparación intra-equipo A1 (efectos de modalidad e insumos): con 274 órdenes y cobertura completa, A1 es la configuración universal para estudiar cómo varían los costos según modalidad y número de insumos.
Comparación intra-equipo B2: análoga a A1 pero con n=44. Las conclusiones son sugestivas, no definitivas.</p>
</div>
</div>
<div id="análisis-condicional-lo-que-revelan-los-estratos" class="section level2 hasAnchor" number="2.7">
<h2><span class="header-section-number">2.7</span> Análisis condicional: lo que revelan los estratos<a href="análisis-exploratorio-básico.html#an%C3%A1lisis-condicional-lo-que-revelan-los-estratos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="efecto-puro-de-tipo_equipo-dentro-de-x-1" class="section level3 hasAnchor" number="2.7.1">
<h3><span class="header-section-number">2.7.1</span> Efecto puro de tipo_equipo dentro de (X, 1)<a href="análisis-exploratorio-básico.html#efecto-puro-de-tipo_equipo-dentro-de-x-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Esta es la pregunta que parecía obvia al inicio: ¿los equipos tienen costos distintos?</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="análisis-exploratorio-básico.html#cb38-1" tabindex="-1"></a>comp_X1 <span class="ot">&lt;-</span> datos_principal <span class="sc">%&gt;%</span></span>
<span id="cb38-2"><a href="análisis-exploratorio-básico.html#cb38-2" tabindex="-1"></a>  <span class="fu">filter</span>(modalidad_proceso <span class="sc">==</span> <span class="st">&quot;X&quot;</span>, num_insumos <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="análisis-exploratorio-básico.html#cb38-3" tabindex="-1"></a>  <span class="fu">group_by</span>(tipo_equipo) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="análisis-exploratorio-básico.html#cb38-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb38-5"><a href="análisis-exploratorio-básico.html#cb38-5" tabindex="-1"></a>    <span class="at">n     =</span> <span class="fu">n</span>(),</span>
<span id="cb38-6"><a href="análisis-exploratorio-básico.html#cb38-6" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb38-7"><a href="análisis-exploratorio-básico.html#cb38-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_transformacion),</span>
<span id="cb38-8"><a href="análisis-exploratorio-básico.html#cb38-8" tabindex="-1"></a>    <span class="at">ds    =</span> <span class="fu">sd</span>(costo_transformacion),</span>
<span id="cb38-9"><a href="análisis-exploratorio-básico.html#cb38-9" tabindex="-1"></a>    <span class="at">IQR   =</span> <span class="fu">IQR</span>(costo_transformacion),</span>
<span id="cb38-10"><a href="análisis-exploratorio-básico.html#cb38-10" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb38-11"><a href="análisis-exploratorio-básico.html#cb38-11" tabindex="-1"></a>  )</span>
<span id="cb38-12"><a href="análisis-exploratorio-básico.html#cb38-12" tabindex="-1"></a>comp_X1</span></code></pre></div>
<pre><code>## # A tibble: 3 × 6
##   tipo_equipo     n media `50%`    ds   IQR
##   &lt;fct&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 A1             60 31.7  29.7  11.7   9.23
## 2 B2              7 29.6  28.9  14.8  19.9 
## 3 D4             55  8.82  8.46  3.54  4.83</code></pre>
<p>Interpretación. Dentro de la única celda donde los tres equipos son comparables:</p>
<p>D4 mantiene un costo de transformación sustancialmente menor.
A1 y B2 son relativamente similares entre sí.
La diferencia entre D4 y los otros equipos es real, no un artefacto de la mezcla de modalidades.</p>
<p>Implicación para la dirección financiera. D4 es efectivamente más eficiente en transformación, al menos en la configuración (X, 1). Sin embargo, el dataset no permite concluir que D4 sería igualmente eficiente en otras modalidades — simplemente porque D4 no puede operar en Y o con 2 insumos.</p>
<p>Este es el análisis más potente del capítulo, porque A1 es el único equipo donde todas las combinaciones tienen n suficiente.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="análisis-exploratorio-básico.html#cb40-1" tabindex="-1"></a>stats_A1 <span class="ot">&lt;-</span> datos_principal <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="análisis-exploratorio-básico.html#cb40-2" tabindex="-1"></a>  <span class="fu">filter</span>(tipo_equipo <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;A1&quot;</span>, <span class="st">&quot;B2&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb40-3"><a href="análisis-exploratorio-básico.html#cb40-3" tabindex="-1"></a>  <span class="fu">group_by</span>(modalidad_proceso, num_insumos) <span class="sc">%&gt;%</span></span>
<span id="cb40-4"><a href="análisis-exploratorio-básico.html#cb40-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb40-5"><a href="análisis-exploratorio-básico.html#cb40-5" tabindex="-1"></a>    <span class="at">n     =</span> <span class="fu">n</span>(),</span>
<span id="cb40-6"><a href="análisis-exploratorio-básico.html#cb40-6" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb40-7"><a href="análisis-exploratorio-básico.html#cb40-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">50%</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">median</span>(costo_transformacion),</span>
<span id="cb40-8"><a href="análisis-exploratorio-básico.html#cb40-8" tabindex="-1"></a>    <span class="at">ds    =</span> <span class="fu">sd</span>(costo_transformacion),</span>
<span id="cb40-9"><a href="análisis-exploratorio-básico.html#cb40-9" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb40-10"><a href="análisis-exploratorio-básico.html#cb40-10" tabindex="-1"></a>  )</span>
<span id="cb40-11"><a href="análisis-exploratorio-básico.html#cb40-11" tabindex="-1"></a>stats_A1</span></code></pre></div>
<pre><code>## # A tibble: 4 × 6
##   modalidad_proceso num_insumos     n media `50%`    ds
##   &lt;fct&gt;             &lt;ord&gt;       &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 X                 1              67  31.4  29.7 12.0 
## 2 X                 2              76  34.8  30.6 15.4 
## 3 Y                 1             136  30.5  29.0 10.7 
## 4 Y                 2              39  34.4  31.7  9.32</code></pre>
<p>Lo que revela el análisis estratificado. Dentro de A1:</p>
<p>El paso de 1 a 2 insumos incrementa el costo de transformación medio de manera consistente en ambas modalidades.
La modalidad Y tiende a tener costos más estables (menor IQR) que la modalidad X.
La combinación (Y, 1) es la más eficiente y la más frecuente (n=118).</p>
<p><strong>la combinación más frecuente del sistema (Y, 1 en A1) es también la más eficiente. ¿Es esto resultado de una estrategia consciente de planeación, o es una coincidencia del perfil de pedidos? La respuesta define si la eficiencia es replicable o circunstancial.</strong></p>
</div>
<div id="efecto-de-número-de-insumos-comparación-condicional" class="section level3 hasAnchor" number="2.7.2">
<h3><span class="header-section-number">2.7.2</span> Efecto de número de insumos: comparación condicional<a href="análisis-exploratorio-básico.html#efecto-de-n%C3%BAmero-de-insumos-comparaci%C3%B3n-condicional" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Un análisis marginal diría que pasar de 1 a 2 insumos aumenta el costo en promedio de 27.3 a 35.8 UM/unidad (+31%). Pero esa comparación mezcla equipos, modalidades y productos.
La comparación condicional dentro de A1 da una respuesta más fina:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="análisis-exploratorio-básico.html#cb42-1" tabindex="-1"></a>efecto_insumos <span class="ot">&lt;-</span> datos_principal <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="análisis-exploratorio-básico.html#cb42-2" tabindex="-1"></a>  <span class="fu">filter</span>(tipo_equipo <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;A1&quot;</span>, <span class="st">&quot;B2&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb42-3"><a href="análisis-exploratorio-básico.html#cb42-3" tabindex="-1"></a>  <span class="fu">group_by</span>(modalidad_proceso, num_insumos) <span class="sc">%&gt;%</span></span>
<span id="cb42-4"><a href="análisis-exploratorio-básico.html#cb42-4" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb42-5"><a href="análisis-exploratorio-básico.html#cb42-5" tabindex="-1"></a>    <span class="at">media_ct =</span> <span class="fu">mean</span>(costo_transformacion),</span>
<span id="cb42-6"><a href="análisis-exploratorio-básico.html#cb42-6" tabindex="-1"></a>    <span class="at">media_ci =</span> <span class="fu">mean</span>(costo_insumo),</span>
<span id="cb42-7"><a href="análisis-exploratorio-básico.html#cb42-7" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span></span>
<span id="cb42-8"><a href="análisis-exploratorio-básico.html#cb42-8" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb42-9"><a href="análisis-exploratorio-básico.html#cb42-9" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> num_insumos,</span>
<span id="cb42-10"><a href="análisis-exploratorio-básico.html#cb42-10" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="fu">c</span>(media_ct, media_ci),</span>
<span id="cb42-11"><a href="análisis-exploratorio-básico.html#cb42-11" tabindex="-1"></a>              <span class="at">names_sep =</span> <span class="st">&quot;_ins&quot;</span>)</span>
<span id="cb42-12"><a href="análisis-exploratorio-básico.html#cb42-12" tabindex="-1"></a>efecto_insumos</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   modalidad_proceso media_ct_ins1 media_ct_ins2 media_ci_ins1 media_ci_ins2
##   &lt;fct&gt;                     &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;
## 1 X                          31.4          34.8          4.09          5.61
## 2 Y                          30.5          34.4          4.79          6.64</code></pre>
<p>El efecto de agregar un segundo insumo es:</p>
<p>En modalidad X: incremento claro en ambos costos.
En modalidad Y: incremento menor en transformación, más marcado en insumo.</p>
<p>Esta es una interacción: el efecto de num_insumos no es el mismo en todas las modalidades. El análisis marginal (el que no estratifica) promedia esas dos realidades y produce un número engañoso.
Implicación financiera. Si la empresa cobra un recargo por órdenes con dos insumos, ese recargo debería depender de la modalidad. Un recargo uniforme subsidia las órdenes complejas en X con los márgenes de las órdenes simples en Y.</p>
</div>
</div>
<div id="asociaciones-numéricas-cuando-la-correlación-cambia-al-estratificar" class="section level2 hasAnchor" number="2.8">
<h2><span class="header-section-number">2.8</span> Asociaciones numéricas: cuando la correlación cambia al estratificar<a href="análisis-exploratorio-básico.html#asociaciones-num%C3%A9ricas-cuando-la-correlaci%C3%B3n-cambia-al-estratificar" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Las correlaciones marginales sobre el dataset principal muestran:</p>
<p>volumen_lote ↔︎ costo_transformacion: −0.35 (Pearson) / −0.27 (Spearman).
duracion_proceso ↔︎ costo_transformacion: +0.22 / +0.28.</p>
<p>Lectura marginal: lotes más grandes son más baratos por unidad (economías de escala), procesos más largos son ligeramente más costosos.
Pero al calcular las mismas correlaciones dentro de A1 y B2 únicamente:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="análisis-exploratorio-básico.html#cb44-1" tabindex="-1"></a>cor_A1_B2 <span class="ot">&lt;-</span> datos_principal <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="análisis-exploratorio-básico.html#cb44-2" tabindex="-1"></a>  <span class="fu">filter</span>(tipo_equipo <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;A1&quot;</span>, <span class="st">&quot;B2&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb44-3"><a href="análisis-exploratorio-básico.html#cb44-3" tabindex="-1"></a>  <span class="fu">select</span>(costo_transformacion, volumen_lote, duracion_proceso,</span>
<span id="cb44-4"><a href="análisis-exploratorio-básico.html#cb44-4" tabindex="-1"></a>         cantidad_insumo_1, cantidad_insumo_2) <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="análisis-exploratorio-básico.html#cb44-5" tabindex="-1"></a>  <span class="fu">cor</span>(<span class="at">use =</span> <span class="st">&quot;pairwise.complete.obs&quot;</span>, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb44-6"><a href="análisis-exploratorio-básico.html#cb44-6" tabindex="-1"></a>  <span class="fu">round</span>(<span class="dv">3</span>)</span>
<span id="cb44-7"><a href="análisis-exploratorio-básico.html#cb44-7" tabindex="-1"></a>cor_A1_B2</span></code></pre></div>
<pre><code>##                      costo_transformacion volumen_lote duracion_proceso
## costo_transformacion                1.000       -0.278            0.139
## volumen_lote                       -0.278        1.000            0.859
## duracion_proceso                    0.139        0.859            1.000
## cantidad_insumo_1                  -0.086        0.731            0.714
## cantidad_insumo_2                   0.124        0.240            0.293
##                      cantidad_insumo_1 cantidad_insumo_2
## costo_transformacion            -0.086             0.124
## volumen_lote                     0.731             0.240
## duracion_proceso                 0.714             0.293
## cantidad_insumo_1                1.000             0.317
## cantidad_insumo_2                0.317             1.000</code></pre>
<p>Por qué importa este contraste. Si la correlación marginal y la correlación dentro de A1 difieren sustancialmente, significa que parte de la relación observada globalmente no es un efecto directo de la variable, sino un efecto de composición: los equipos con ciertos perfiles de volumen también tienen ciertos perfiles de costo, y eso infla o deforma la correlación marginal.
Traducción financiera. Las economías de escala son reales dentro de A1, pero el tamaño del efecto marginal que ven los reportes tradicionales puede estar sobrestimado porque mezcla el efecto de “producir más” con el efecto de “producir en un equipo distinto”.</p>
</div>
<div id="caracterización-descriptiva-de-los-subconjuntos-excluidos" class="section level2 hasAnchor" number="2.9">
<h2><span class="header-section-number">2.9</span> Caracterización descriptiva de los subconjuntos excluidos<a href="análisis-exploratorio-básico.html#caracterizaci%C3%B3n-descriptiva-de-los-subconjuntos-excluidos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Esta sección es puramente descriptiva. No se hacen inferencias, solo se documentan los subconjuntos excluidos del análisis principal para transparencia.
### Modalidad Z (n=14)
datos %&gt;%
filter(modalidad_proceso == “Z”) %&gt;%
group_by(tipo_equipo) %&gt;%
summarise(
n = n(),
ct_media = mean(costo_transformacion),
ci_media = mean(costo_insumo),
ctot_media = mean(costo_unitario_total),
.groups = “drop”
)
Observación descriptiva. Las órdenes en modalidad Z presentan un costo total promedio superior al de X y Y en A1. Esto es consistente con la definición operativa de Z (aplicación conjunta de X e Y al mismo producto), que implica mayor consumo de tiempo y recursos. La magnitud exacta del sobrecosto no es generalizable con n=14 y no se usará para ninguna conclusión. Solo sirve como referencia cualitativa para que la empresa calibre el recargo comercial aplicado a pedidos que solicitan Z.
### Tipo de equipo C3 (n=8)
datos %&gt;%
filter(tipo_equipo == “C3”) %&gt;%
summarise(
n = n(),
ct_media = mean(costo_transformacion),
ct_mediana = median(costo_transformacion),
ci_media = mean(costo_insumo),
ci_mediana = median(costo_insumo)
)
Observación descriptiva. C3 presenta los costos más altos del dataset tanto en transformación como en insumos. Con n=8 el intervalo de confianza es demasiado amplio para afirmar cuánto más costoso es en comparación con otros equipos, pero el patrón es consistente y amerita una revisión operativa específica —fuera del alcance de este trabajo estadístico— sobre qué justifica su uso y en qué condiciones.</p>
<p>6.9 Síntesis: lo que cambia para el capítulo de inferencia
6.9.1 Qué se puede afirmar después del EDA</p>
<p>El sistema productivo no es homogéneo: tiene al menos tres regímenes operativos diferenciados por tipo de equipo (A1/B2 como regímenes estándar, D4 como régimen eficiente restringido a (X, 1), C3 como régimen excepcional).
Dentro de A1 (configuración universal), el número de insumos y la modalidad afectan el costo de manera interactiva. El efecto de agregar un segundo insumo depende de la modalidad.
Las economías de escala son reales pero no uniformes: pierden intensidad en volúmenes altos y presentan mayor dispersión en lotes pequeños.
El costo de transformación domina el costo total (85%). Cualquier iniciativa de reducción debe enfocarse en procesos, no en insumos.</p>
<p>6.9.2 Hipótesis que alimentan el capítulo 7 (inferencia)
Con base en el EDA, las pruebas inferenciales formales que tienen sustento son:
HipótesisPrueba aplicableEstratonH1: El costo de transformación difiere entre A1, B2 y D4ANOVA 1 vía (Welch) o Kruskal-Wallis(X, 1) únicamente122H2: Dentro de A1, la modalidad afecta el costot-test o Mann-WhitneyA1 completo274H3: Dentro de A1, el número de insumos afecta el costot-test o Mann-WhitneyA1 completo274H4: Existe interacción modalidad × num_insumos dentro de A1ANOVA 2 víasA1 completo274H5: Existe correlación entre volumen_lote y costo dentro de A1Correlación de Spearman con ICA1 completo274
6.9.3 Comparaciones que el diseño del dataset no permite hacer
Para transparencia metodológica, se documenta lo que el dataset no puede responder:</p>
<p>Si D4 sería más eficiente que A1 en modalidad Y: D4 nunca operó en Y.
Si C3 sería competitivo con volúmenes altos: los 8 casos de C3 no cubren rangos altos de volumen.
Si la modalidad Z es más costosa que la suma de X e Y: n=14 no da potencia suficiente.</p>
<p>Estas preguntas requerirían un diseño de recolección de datos distinto, con asignación deliberada de órdenes a configuraciones específicas para romper la dependencia entre factores.</p>
<p>6.10 Implicaciones para la dirección financiera
Cuatro mensajes para la toma de decisiones:</p>
<p>La reducción de costos tiene un techo estructural del 15% si se enfoca solo en insumos. La palanca mayor está en los procesos de transformación, específicamente en los regímenes menos eficientes.
D4 es el equipo más eficiente observado, pero su alcance es limitado. Antes de recomendar migración de producción, se requiere un estudio operativo que determine si las restricciones de D4 son técnicas o históricas.
La política de precios probablemente está subsidiando la complejidad. Las órdenes con dos insumos son sistemáticamente más costosas, pero el recargo aplicado (si existe) no varía por modalidad. Órdenes complejas en modalidad X son las menos rentables.
El tamaño de lote mínimo rentable debe definirse explícitamente. Los lotes pequeños concentran los mayores costos unitarios y la mayor variabilidad. Una política de lote mínimo, o una estructura de precios que incentive la consolidación de pedidos, tendría impacto medible e inmediato.</p>
<p>Nota final sobre el método. Este capítulo deliberadamente empezó con una visión agregada y la desmontó progresivamente. El objetivo no fue mostrar los hallazgos de la forma más eficiente, sino hacer visible el razonamiento: cómo una primera lectura simple escondía una estructura jerárquica, por qué el análisis marginal era engañoso, y qué comparaciones sí son válidas en un dataset con espacio operativo truncado. Esta disciplina es la que separa un EDA mecánico de un EDA con criterio.</p>

</div>
<div id="estratificado" class="section level2 hasAnchor" number="2.10">
<h2><span class="header-section-number">2.10</span> estratificado<a href="análisis-exploratorio-básico.html#estratificado" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="diccionario-de-campos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="pruebas-de-hipótesis-sin-desarrollar.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "serif",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": {},
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "toolbar": {
    "position": "static"
  }
});
});
</script>

</body>

</html>
