<!DOCTYPE html>
<html lang="es" xml:lang="es">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Prefacio | Análisis exploratorio e inferencial</title>
  <meta name="description" content="Maestría en Estadística Aplicada." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Prefacio | Análisis exploratorio e inferencial" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Maestría en Estadística Aplicada." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Prefacio | Análisis exploratorio e inferencial" />
  
  <meta name="twitter:description" content="Maestría en Estadística Aplicada." />
  

<meta name="author" content="Gloria Bastidas" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="portada.html"/>
<link rel="next" href="diccionario-de-campos.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Libro Académico</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="portada.html"><a href="portada.html"><i class="fa fa-check"></i>Portada</a></li>
<li class="chapter" data-level="" data-path="prefacio.html"><a href="prefacio.html"><i class="fa fa-check"></i>Prefacio</a>
<ul>
<li class="chapter" data-level="0.0.1" data-path="prefacio.html"><a href="prefacio.html#verificaci%C3%B3n-de-la-lectura"><i class="fa fa-check"></i><b>0.0.1</b> Verificación de la lectura</a></li>
<li class="chapter" data-level="0.0.2" data-path="prefacio.html"><a href="prefacio.html#revisi%C3%B3n-de-integridad-de-datos"><i class="fa fa-check"></i><b>0.0.2</b> Revisión de integridad de datos</a></li>
<li class="chapter" data-level="0.0.3" data-path="prefacio.html"><a href="prefacio.html#conversi%C3%B3n-de-tipos"><i class="fa fa-check"></i><b>0.0.3</b> Conversión de tipos</a></li>
<li class="chapter" data-level="0.0.4" data-path="prefacio.html"><a href="prefacio.html#consideraciones-estructurales-para-el-an%C3%A1lisis"><i class="fa fa-check"></i><b>0.0.4</b> Consideraciones estructurales para el análisis</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="diccionario-de-campos.html"><a href="diccionario-de-campos.html"><i class="fa fa-check"></i><b>1</b> Diccionario de campos</a></li>
<li class="chapter" data-level="2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html"><i class="fa fa-check"></i><b>2</b> Análisis Exploratorio Básico</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#carga-del-dataset-anal%C3%ADtico"><i class="fa fa-check"></i><b>2.1</b> Carga del dataset analítico</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-variables-respuesta"><i class="fa fa-check"></i><b>2.2</b> Análisis univariado de variables respuesta</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#costo-unitario-de-conversi%C3%B3n-o-de-transformacion"><i class="fa fa-check"></i><b>2.2.1</b> Costo unitario de conversión o de transformacion</a></li>
<li class="chapter" data-level="2.2.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#costo-unitario-de-los-insumos"><i class="fa fa-check"></i><b>2.2.2</b> Costo unitario de los insumos</a></li>
<li class="chapter" data-level="2.2.3" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#costo-unitario-total"><i class="fa fa-check"></i><b>2.2.3</b> Costo unitario total</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-predictoras-num%C3%A9ricas"><i class="fa fa-check"></i><b>2.3</b> Análisis univariado de predictoras numéricas</a></li>
<li class="chapter" data-level="2.4" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-univariado-de-predictoras-categ%C3%B3ricas"><i class="fa fa-check"></i><b>2.4</b> 6.4 Análisis univariado de predictoras categóricas</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-modalidad-proceso"><i class="fa fa-check"></i><b>2.4.1</b> Análisis bivariado: Modalidad proceso</a></li>
<li class="chapter" data-level="2.4.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-tipo-de-equipo"><i class="fa fa-check"></i><b>2.4.2</b> Análisis bivariado: tipo de equipo</a></li>
<li class="chapter" data-level="2.4.3" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-bivariado-equipo_id"><i class="fa fa-check"></i><b>2.4.3</b> Análisis bivariado: Equipo_id</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#decisiones-metodol%C3%B3gicas-derivadas-del-eda-inicial"><i class="fa fa-check"></i><b>2.5</b> Decisiones metodológicas derivadas del EDA inicial</a></li>
<li class="chapter" data-level="2.6" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#estructura-del-espacio-operativo-sobre-el-dataset-principal"><i class="fa fa-check"></i><b>2.6</b> Estructura del espacio operativo sobre el dataset principal</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#mapa-de-combinaciones"><i class="fa fa-check"></i><b>2.6.1</b> Mapa de combinaciones</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#an%C3%A1lisis-condicional-lo-que-revelan-los-estratos"><i class="fa fa-check"></i><b>2.7</b> Análisis condicional: lo que revelan los estratos</a>
<ul>
<li class="chapter" data-level="2.7.1" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#efecto-puro-de-tipo_equipo-dentro-de-x-1"><i class="fa fa-check"></i><b>2.7.1</b> Efecto puro de tipo_equipo dentro de (X, 1)</a></li>
<li class="chapter" data-level="2.7.2" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#efecto-de-n%C3%BAmero-de-insumos-comparaci%C3%B3n-condicional"><i class="fa fa-check"></i><b>2.7.2</b> Efecto de número de insumos: comparación condicional</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#asociaciones-num%C3%A9ricas-cuando-la-correlaci%C3%B3n-cambia-al-estratificar"><i class="fa fa-check"></i><b>2.8</b> Asociaciones numéricas: cuando la correlación cambia al estratificar</a></li>
<li class="chapter" data-level="2.9" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#caracterizaci%C3%B3n-descriptiva-de-los-subconjuntos-excluidos"><i class="fa fa-check"></i><b>2.9</b> Caracterización descriptiva de los subconjuntos excluidos</a></li>
<li class="chapter" data-level="2.10" data-path="análisis-exploratorio-básico.html"><a href="análisis-exploratorio-básico.html#estratificado"><i class="fa fa-check"></i><b>2.10</b> estratificado</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="pruebas-de-hipótesis-sin-desarrollar.html"><a href="pruebas-de-hipótesis-sin-desarrollar.html"><i class="fa fa-check"></i><b>3</b> Pruebas de Hipótesis SIN DESARROLLAR</a></li>
<li class="chapter" data-level="4" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html"><i class="fa fa-check"></i><b>4</b> Modelos SIN DESARROLLAR</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html#ajuste-del-modelo"><i class="fa fa-check"></i><b>4.1</b> Ajuste del modelo</a></li>
<li class="chapter" data-level="4.2" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html#medidas-de-ajuste"><i class="fa fa-check"></i><b>4.2</b> Medidas de ajuste</a></li>
<li class="chapter" data-level="4.3" data-path="modelos-sin-desarrollar.html"><a href="modelos-sin-desarrollar.html#gr%C3%A1fico-de-observados-vs-ajustados"><i class="fa fa-check"></i><b>4.3</b> Gráfico de observados vs ajustados</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="conclusión.html"><a href="conclusión.html"><i class="fa fa-check"></i><b>5</b> Conclusión</a></li>
<li class="chapter" data-level="6" data-path="bibliografía.html"><a href="bibliografía.html"><i class="fa fa-check"></i><b>6</b> Bibliografía</a></li>
<li class="divider"></li>
<li><a href="https://github.com/">Publicado con GitHub Pages</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis exploratorio e inferencial</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="prefacio" class="section level1 unnumbered hasAnchor">
<h1>Prefacio<a href="prefacio.html#prefacio" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Este libro presenta una estructura reproducible y académica para documentar un proyecto de análisis estadístico usando <strong>R</strong>, <strong>bookdown</strong>, <strong>GitHub Codespaces</strong> y <strong>GitHub Pages</strong>.</p>
<p>Se recomienda mantener todos los datos en la carpeta <code>data/</code>, todas las imágenes en <code>images/</code> y todas las referencias en <code>references.bib</code>.</p>
<p>vx</p>
<p>options(scipen = 999)</p>
<p>library(tidyverse)
library(janitor)
library(skimr)
library(knitr)
library(kableExtra)
library(broom)
library(here)</p>
<p>ruta_datos &lt;- “data/datos_ejemplo.csv”</p>
<p>if (file.exists(ruta_datos)) {
datos &lt;- readr::read_csv(ruta_datos, show_col_types = FALSE) |&gt;
janitor::clean_names()
} else {
datos &lt;- mtcars |&gt;
tibble::rownames_to_column(“modelo”) |&gt;
janitor::clean_names()
}</p>
<pre><code>
&lt;!--chapter:end:index.Rmd--&gt;

# Resumen

SIN INICIAR

&lt;!--chapter:end:01-resumen.Rmd--&gt;

# Introducción

La manufactura farmacéutica opera bajo presión creciente sobre sus márgenes. Los costos de conversión y de insumos representan en conjunto la mayor parte del costo de ventas en empresas de formas sólidas, y su variabilidad entre órdenes de producción puede comprometer la rentabilidad unitaria y la calidad de la información para la toma de decisiones (Basu et al., 2008; Suresh &amp; Basu, 2008). En la práctica, los sistemas ERP registran centenares de órdenes por mes con decenas de atributos, pero los responsables de planeación rara vez disponen de evidencia estadística sobre cuáles de esos atributos explican la dispersión del costo unitario observado.

La investigación académica sobre determinantes del costo ha evolucionado en tres olas sucesivas. Foster y Gupta (1990) abrieron la tradición empírica al mostrar, con datos de 37 plantas de electrónica, que el volumen es un predictor fuerte del overhead, mientras que variables de complejidad y eficiencia resultan débiles una vez controlado el tamaño. Banker et al. (1995) matizaron esa conclusión: al especificar variables transaccionales como órdenes de cambio de ingeniería y personal de planeación, los autores encontraron que las transacciones explican una proporción mayor de la varianza de overhead que el propio volumen. Paralelamente, Cooper y Kaplan (1988, 1992) articularon el marco conceptual del costeo basado en actividades, en el que la regresión múltiple ocupa un rol central para identificar y validar drivers. Anderson, Banker y Janakiraman (2003), una década después, documentaron con 7,629 empresas un fenómeno que la tradición anterior no contemplaba: los costos responden de forma asimétrica a variaciones de volumen, comportamiento conocido como &#39;sticky costs&#39;.

En paralelo, la ingeniería de costos desarrolló una taxonomía complementaria. Niazi et al. (2006) sistematizaron las técnicas de estimación de costo de producto y ubicaron la regresión dentro de los métodos paramétricos y analógicos. Trabajos posteriores han comparado la regresión lineal con redes neuronales y métodos de ensemble en distintos sectores (Cavalieri et al., 2004; Loyer et al., 2016), con un consenso emergente: los métodos no lineales mejoran la precisión cuando se dispone de volúmenes grandes de datos homogéneos, pero la regresión lineal conserva ventajas de interpretabilidad que son críticas cuando el objetivo es explicar —no solo predecir— la variabilidad del costo.

La literatura específica sobre manufactura farmacéutica es más reducida y se orienta hacia dos focos: el costo de biosimilares y anticuerpos monoclonales (Basu et al., 2008) y la comparación económica entre tecnologías batch y continuas en formas sólidas (Matsunami et al., 2018). Estos trabajos identifican el tamaño de lote, el tipo de proceso y el rendimiento como drivers principales, pero no modelan estadísticamente la variabilidad del costo unitario a nivel de orden de producción. La escasez de estudios con esta granularidad, en particular en contextos latinoamericanos, constituye un vacío que este trabajo aborda.

El problema que motiva esta tesis se ubica en una empresa farmacéutica colombiana productora de cápsulas duras y medicamentos. La empresa cuenta con 406 órdenes de producción registradas en su ERP con información estructurada sobre ocho atributos operativos: modelo de máquina, máquina individual, tamaño de lote, número de insumos, tipo de insumos, referencia de insumos, tipo de proceso y tamaño del producto. El análisis descriptivo previo muestra una dispersión notable del costo unitario de conversión y del costo unitario de insumos entre órdenes, sin que exista claridad sobre cuáles atributos explican esa variabilidad. La hipótesis de trabajo es que las variables operativas mencionadas, de forma conjunta y con interacciones, explican una proporción sustancial de la variabilidad observada, y que su cuantificación estadística permite priorizar acciones correctivas en planeación y en calidad de datos del ERP.

La regresión lineal múltiple se elige como técnica principal por cuatro razones. Primero, por su alineación con la tradición empírica dominante en la literatura de cost drivers (Foster &amp; Gupta, 1990; Banker et al., 1995; Anderson et al., 2003). Segundo, por su interpretabilidad: los coeficientes parciales permiten atribuir variación a cada driver controlando por los demás, lo cual es indispensable para el diálogo con el área financiera y de operaciones. Tercero, por su compatibilidad con pruebas diagnósticas estandarizadas (multicolinealidad, heterocedasticidad, normalidad de residuos) documentadas en textos metodológicos de referencia (Montgomery et al., 2021; Hair et al., 2018). Cuarto, porque el tamaño muestral de 406 órdenes permite estimar con razonable potencia modelos con variables categóricas codificadas como dummies, complementables con regularización Lasso o Ridge cuando la colinealidad o la alta cardinalidad lo exijan (James et al., 2021).

El aporte del estudio se articula en tres ejes. En el eje teórico, extiende la evidencia empírica sobre cost drivers al sector de manufactura farmacéutica de formas sólidas, poco representado en la literatura internacional. En el eje metodológico, combina regresión múltiple con variables categóricas de alta cardinalidad a nivel de orden, modela dos variables respuesta complementarias (conversión e insumos) y contrasta la especificación lineal con alternativas regularizadas. En el eje aplicado, entrega a la empresa un conjunto de coeficientes interpretables, un ranking de drivers por poder explicativo, y recomendaciones concretas de planeación y de mejora del registro de datos en el ERP, lo cual conecta directamente con la línea de investigación de calidad de datos transaccionales que la autora viene desarrollando.

&lt;!--chapter:end:02-introduccion.Rmd--&gt;

# Objetivos EN CONSTRUCCCION

## Objetivo general

Analizar y cuantificar el impacto de diversos factores productivos (equipos, modalidades, productos, insumos, tiempo y volumen) sobre el costo unitario, utilizando métodos paramétricos y no paramétricos para fundamentar la toma de decisiones en evidencia técnica.

## Objetivos específicos

1. Analizar las diferencias entre tipos de equipo y su impacto en el costo
2. Investigar si existe igualdad de medias en los equipos de un mismo tipo.
3. Explorar la correlación entre el costo unitario y el tiempo de conversión.
4. Evaluar la correlación entre el costo unitario, el número de insumos y el tipo de insumos.

&lt;!--chapter:end:03-objetivos.Rmd--&gt;

# Metodología {#metodologia}

Este capítulo documenta el diseño metodológico del estudio, el proceso de obtención de los datos desde el sistema ERP, y los procedimientos de carga, verificación de integridad y depuración aplicados antes del análisis estadístico. Al final del capítulo, el dataset analítico queda conformado por las órdenes de producción que cumplen los criterios de completitud y validez operativa.

## Diseño del estudio

Este trabajo corresponde a un **estudio observacional, retrospectivo y transversal** sobre el proceso productivo de una empresa farmacéutica colombiana. Es observacional porque no se manipulan variables sobre el proceso; retrospectivo porque utiliza registros generados durante operaciones ya ejecutadas; y transversal porque captura información de un período acotado sin seguimiento longitudinal de unidades individuales.

La muestra inicial está conformada por 404 órdenes de producción registradas en el sistema ERP durante el período de estudio, extraídas mediante consultas SQL sobre las tablas transaccionales de órdenes, consumos y tiempos, junto con la tabla de costos por período y el maestro de productos. La consolidación se realizó en Excel y posteriormente se exportó a formato CSV para garantizar reproducibilidad y trazabilidad. Tras la depuración de registros inválidos documentada en la sección 4.2.3, el dataset analítico final queda conformado por las órdenes que cubren la variedad de productos, equipos, modalidades y tamaños de lote habituales del proceso.

**Limitaciones conocidas del dataset:**

- **Sesgo de selección:** se excluyen registros de órdenes anuladas, abortadas o reprocesadas, limitándose exclusivamente a procesos completados.
- **Variabilidad operativa:** la calidad del registro depende de la disciplina del operario en el momento de cierre de la orden en el ERP, lo cual introduce una fuente de error de medición no cuantificable a priori.
- **Imprecisión en consumos:** los insumos se registran en litros equivalentes a un envase estándar; las fracciones menores se estiman visualmente ante la falta de un proceso de pesaje, lo que afecta la precisión de las cantidades reportadas.
- **Base de valoración:** los costos se expresan en unidades monetarias por producto, calculados según la tarifa de costeo del período reportado.

**Aspectos éticos y de confidencialidad.** Los datos provienen de operaciones industriales reales y contienen información sensible para la empresa. Por esta razón, los identificadores de producto, máquina e insumo fueron anonimizados en origen mediante codificación alfanumérica que preserva la estructura analítica sin revelar identidades comerciales.

**Software.** Los análisis se realizan en R versión 4 o superior, con los paquetes `tidyverse` para manipulación y visualización, `Amelia` para diagnóstico de valores faltantes, `janitor` como guardia defensiva en limpieza de nombres, `kableExtra` para presentación de tablas, y `patchwork` y `gridExtra` para composición de gráficos. Todos los análisis son completamente reproducibles a partir del código fuente disponible en el repositorio.

## Extracción, transformación y carga (ETL)

### Carga del conjunto de datos

El archivo CSV exportado desde el consolidado Excel utiliza punto y coma (`;`) como separador de columnas y punto (`.`) como separador decimal. Dado que `read_csv2` asume coma como decimal y `read_csv` asume coma como separador, se utiliza `read_delim` con especificación explícita de ambos parámetros.


``` r
library(tidyverse)
library(janitor)
library(Amelia)

datos &lt;- read_delim(&quot;data/data_costos.csv&quot;,
                    delim = &quot;;&quot;,
                    locale = locale(decimal_mark = &quot;.&quot;, encoding = &quot;UTF-8&quot;),
                    show_col_types = FALSE)</code></pre>
<div id="verificación-de-la-lectura" class="section level3 hasAnchor" number="0.0.1">
<h3><span class="header-section-number">0.0.1</span> Verificación de la lectura<a href="prefacio.html#verificaci%C3%B3n-de-la-lectura" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Verificamos que el archivo se leyó correctamente inspeccionando las primeras filas, las dimensiones, los nombres de las columnas y la estructura de tipos detectados.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="prefacio.html#cb2-1" tabindex="-1"></a><span class="fu">head</span>(datos, <span class="at">n =</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## # A tibble: 5 × 16
##   periodo codigo_producto id_orden volumen_lote costo_transformacion
##     &lt;dbl&gt; &lt;chr&gt;              &lt;dbl&gt;        &lt;dbl&gt;                &lt;dbl&gt;
## 1  202501 P05747            546009         7440                 24.6
## 2  202501 P06976            551645         1680                 36.5
## 3  202501 P07920            548767         1556                 22.3
## 4  202501 P07767            552185         2700                 14.2
## 5  202501 P07576            546482         2578                 18.2
## # ℹ 11 more variables: costo_insumo &lt;dbl&gt;, equipo_id &lt;chr&gt;, tipo_equipo &lt;chr&gt;,
## #   categoria_producto &lt;dbl&gt;, num_insumos &lt;dbl&gt;, insumo_1 &lt;chr&gt;,
## #   insumo_2 &lt;chr&gt;, cantidad_insumo_1 &lt;dbl&gt;, cantidad_insumo_2 &lt;dbl&gt;,
## #   modalidad_proceso &lt;chr&gt;, duracion_proceso &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="prefacio.html#cb4-1" tabindex="-1"></a><span class="fu">dim</span>(datos)</span></code></pre></div>
<pre><code>## [1] 404  16</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="prefacio.html#cb6-1" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code></pre></div>
<pre><code>##  [1] &quot;periodo&quot;              &quot;codigo_producto&quot;      &quot;id_orden&quot;            
##  [4] &quot;volumen_lote&quot;         &quot;costo_transformacion&quot; &quot;costo_insumo&quot;        
##  [7] &quot;equipo_id&quot;            &quot;tipo_equipo&quot;          &quot;categoria_producto&quot;  
## [10] &quot;num_insumos&quot;          &quot;insumo_1&quot;             &quot;insumo_2&quot;            
## [13] &quot;cantidad_insumo_1&quot;    &quot;cantidad_insumo_2&quot;    &quot;modalidad_proceso&quot;   
## [16] &quot;duracion_proceso&quot;</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="prefacio.html#cb8-1" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div>
<pre><code>## spc_tbl_ [404 × 16] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ periodo             : num [1:404] 202501 202501 202501 202501 202501 ...
##  $ codigo_producto     : chr [1:404] &quot;P05747&quot; &quot;P06976&quot; &quot;P07920&quot; &quot;P07767&quot; ...
##  $ id_orden            : num [1:404] 546009 551645 548767 552185 546482 ...
##  $ volumen_lote        : num [1:404] 7440 1680 1556 2700 2578 ...
##  $ costo_transformacion: num [1:404] 24.6 36.5 22.3 14.2 18.2 ...
##  $ costo_insumo        : num [1:404] 4.18 1.59 2.15 3.84 2.08 ...
##  $ equipo_id           : chr [1:404] &quot;M08&quot; &quot;M02&quot; &quot;M14&quot; &quot;M13&quot; ...
##  $ tipo_equipo         : chr [1:404] &quot;A1&quot; &quot;B2&quot; &quot;A1&quot; &quot;A1&quot; ...
##  $ categoria_producto  : num [1:404] 7 5 5 5 5 5 5 5 5 4 ...
##  $ num_insumos         : num [1:404] 1 2 1 1 2 2 2 2 1 1 ...
##  $ insumo_1            : chr [1:404] &quot;B_T&quot; &quot;B_T&quot; &quot;N_O&quot; &quot;B_T&quot; ...
##  $ insumo_2            : chr [1:404] NA &quot;N_T&quot; NA NA ...
##  $ cantidad_insumo_1   : num [1:404] 6 1.5 0.5 2 2 2 2 2 1.3 2.5 ...
##  $ cantidad_insumo_2   : num [1:404] 0 0.05 0 0 0.05 0.05 0.05 0.5 0 0 ...
##  $ modalidad_proceso   : chr [1:404] &quot;X&quot; &quot;Y&quot; &quot;Y&quot; &quot;X&quot; ...
##  $ duracion_proceso    : num [1:404] 300 98 100 62 91 ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   periodo = col_double(),
##   ..   codigo_producto = col_character(),
##   ..   id_orden = col_double(),
##   ..   volumen_lote = col_double(),
##   ..   costo_transformacion = col_double(),
##   ..   costo_insumo = col_double(),
##   ..   equipo_id = col_character(),
##   ..   tipo_equipo = col_character(),
##   ..   categoria_producto = col_double(),
##   ..   num_insumos = col_double(),
##   ..   insumo_1 = col_character(),
##   ..   insumo_2 = col_character(),
##   ..   cantidad_insumo_1 = col_double(),
##   ..   cantidad_insumo_2 = col_double(),
##   ..   modalidad_proceso = col_character(),
##   ..   duracion_proceso = col_double()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;externalptr&gt;</code></pre>
<p>El conjunto de datos contiene 404 órdenes de producción y 16 variables, conforme a la definición presentada en el capítulo del diccionario de datos. Los costos <code>costo_transformacion</code> y <code>costo_insumo</code>, así como las cantidades de insumo, se leyeron correctamente como numéricos de tipo <code>double</code>. El significado, tipo analítico, unidad de medida y rol de cada una de las 16 variables se documenta en detalle en el siguiente capítulo.</p>
</div>
<div id="revisión-de-integridad-de-datos" class="section level3 hasAnchor" number="0.0.2">
<h3><span class="header-section-number">0.0.2</span> Revisión de integridad de datos<a href="prefacio.html#revisi%C3%B3n-de-integridad-de-datos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La revisión de integridad se estructura en tres dimensiones analíticas que pueden solaparse o converger según la naturaleza de las variables:</p>
<ol style="list-style-type: decimal">
<li><strong>Cadenas vacías:</strong> marcadores de ausencia implícita en variables de tipo texto.</li>
<li><strong>Valores NA:</strong> ausencia explícita de información en el sistema.</li>
<li><strong>Valores con magnitud cero:</strong> registros presentes en el dataset pero con valor numérico cero. Dado que las variables analizadas corresponden a costos, volúmenes y tiempos de proceso, la presencia de valores cero carece de sustento teórico, ya que no es consistente con la naturaleza de estas magnitudes.</li>
</ol>
<div id="cadenas-vacías" class="section level4 hasAnchor" number="0.0.2.1">
<h4><span class="header-section-number">0.0.2.1</span> Cadenas vacías<a href="prefacio.html#cadenas-vac%C3%ADas" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="prefacio.html#cb10-1" tabindex="-1"></a>conteo_vacios <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="prefacio.html#cb10-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">trimws</span>(<span class="fu">as.character</span>(.)) <span class="sc">==</span> <span class="st">&quot;&quot;</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="prefacio.html#cb10-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;n_vacios&quot;</span>)</span>
<span id="cb10-4"><a href="prefacio.html#cb10-4" tabindex="-1"></a></span>
<span id="cb10-5"><a href="prefacio.html#cb10-5" tabindex="-1"></a>total_vacios <span class="ot">&lt;-</span> <span class="fu">sum</span>(conteo_vacios<span class="sc">$</span>n_vacios)</span>
<span id="cb10-6"><a href="prefacio.html#cb10-6" tabindex="-1"></a></span>
<span id="cb10-7"><a href="prefacio.html#cb10-7" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(conteo_vacios, <span class="at">caption =</span> <span class="st">&quot;Conteo de cadenas vacías por variable&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-8"><a href="prefacio.html#cb10-8" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-9"><a href="prefacio.html#cb10-9" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">width =</span> <span class="st">&quot;12em&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-10"><a href="prefacio.html#cb10-10" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">2</span>, <span class="at">width =</span> <span class="st">&quot;12em&quot;</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:conteo-vacios">Table 0.1: </span><span id="tab:conteo-vacios">Table 0.2: </span>Conteo de cadenas vacías por variable
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:right;">
n_vacios
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 12em; ">
periodo
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
codigo_producto
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
id_orden
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
volumen_lote
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
costo_transformacion
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
costo_insumo
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
equipo_id
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
tipo_equipo
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
categoria_producto
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
num_insumos
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
insumo_1
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
insumo_2
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
cantidad_insumo_1
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
cantidad_insumo_2
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
modalidad_proceso
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
duracion_proceso
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
</tbody>
</table>
<p>Se identificaron 0 cadenas vacías en el dataset. No se requiere intervención en esta dimensión de integridad.</p>
</div>
<div id="valores-na" class="section level4 hasAnchor" number="0.0.2.2">
<h4><span class="header-section-number">0.0.2.2</span> Valores NA<a href="prefacio.html#valores-na" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="prefacio.html#cb11-1" tabindex="-1"></a>conteo_na <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="prefacio.html#cb11-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)))) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="prefacio.html#cb11-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;n_na&quot;</span>)</span>
<span id="cb11-4"><a href="prefacio.html#cb11-4" tabindex="-1"></a></span>
<span id="cb11-5"><a href="prefacio.html#cb11-5" tabindex="-1"></a>tabla_na <span class="ot">&lt;-</span> conteo_na <span class="sc">%&gt;%</span> <span class="fu">filter</span>(n_na <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb11-6"><a href="prefacio.html#cb11-6" tabindex="-1"></a></span>
<span id="cb11-7"><a href="prefacio.html#cb11-7" tabindex="-1"></a>total_na       <span class="ot">&lt;-</span> <span class="fu">sum</span>(conteo_na<span class="sc">$</span>n_na)</span>
<span id="cb11-8"><a href="prefacio.html#cb11-8" tabindex="-1"></a>n_vars_con_na  <span class="ot">&lt;-</span> <span class="fu">nrow</span>(tabla_na)</span>
<span id="cb11-9"><a href="prefacio.html#cb11-9" tabindex="-1"></a>n_na_insumo_1  <span class="ot">&lt;-</span> conteo_na <span class="sc">%&gt;%</span> <span class="fu">filter</span>(variable <span class="sc">==</span> <span class="st">&quot;insumo_1&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(n_na)</span>
<span id="cb11-10"><a href="prefacio.html#cb11-10" tabindex="-1"></a>n_na_insumo_2  <span class="ot">&lt;-</span> conteo_na <span class="sc">%&gt;%</span> <span class="fu">filter</span>(variable <span class="sc">==</span> <span class="st">&quot;insumo_2&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(n_na)</span>
<span id="cb11-11"><a href="prefacio.html#cb11-11" tabindex="-1"></a>pct_na_insumo_2 <span class="ot">&lt;-</span> <span class="fu">round</span>(n_na_insumo_2 <span class="sc">/</span> n_filas_inicial <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb11-12"><a href="prefacio.html#cb11-12" tabindex="-1"></a></span>
<span id="cb11-13"><a href="prefacio.html#cb11-13" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tabla_na, <span class="at">caption =</span> <span class="st">&quot;Variables con valores NA&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-14"><a href="prefacio.html#cb11-14" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-15"><a href="prefacio.html#cb11-15" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">width =</span> <span class="st">&quot;12em&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-16"><a href="prefacio.html#cb11-16" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">2</span>, <span class="at">width =</span> <span class="st">&quot;12em&quot;</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:conteo-na">Table 0.3: </span><span id="tab:conteo-na">Table 0.4: </span>Variables con valores NA
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:right;">
n_na
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 12em; ">
insumo_1
</td>
<td style="text-align:right;width: 12em; ">
8
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
insumo_2
</td>
<td style="text-align:right;width: 12em; ">
279
</td>
</tr>
</tbody>
</table>
<p>El conteo absoluto muestra un total de 287 valores NA distribuidos en 2 variables del dataset. La variable <code>insumo_2</code> concentra 279 ausencias, equivalentes al 69.1% de las 404 órdenes; conforme a las consultas SQL de origen, estos NA no representan datos perdidos sino la ausencia estructural de un segundo insumo cuando <code>num_insumos &lt; 2</code>, y se recodifican en la sección 4.2.4 como una categoría explícita. La variable <code>insumo_1</code> presenta 8 ausencias, las cuales se investigan en la siguiente sección junto con los valores cero, dado que ambos fenómenos tienden a coincidir en los mismos registros.</p>
</div>
<div id="valores-con-magnitud-cero" class="section level4 hasAnchor" number="0.0.2.3">
<h4><span class="header-section-number">0.0.2.3</span> Valores con magnitud cero<a href="prefacio.html#valores-con-magnitud-cero" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="prefacio.html#cb12-1" tabindex="-1"></a>conteo_ceros <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="prefacio.html#cb12-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">sum</span>(. <span class="sc">==</span> <span class="dv">0</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="prefacio.html#cb12-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>(), <span class="at">names_to =</span> <span class="st">&quot;variable&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;n_ceros&quot;</span>)</span>
<span id="cb12-4"><a href="prefacio.html#cb12-4" tabindex="-1"></a></span>
<span id="cb12-5"><a href="prefacio.html#cb12-5" tabindex="-1"></a>total_ceros <span class="ot">&lt;-</span> <span class="fu">sum</span>(conteo_ceros<span class="sc">$</span>n_ceros)</span>
<span id="cb12-6"><a href="prefacio.html#cb12-6" tabindex="-1"></a></span>
<span id="cb12-7"><a href="prefacio.html#cb12-7" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(conteo_ceros, <span class="at">caption =</span> <span class="st">&quot;Conteo de valores cero por variable numérica&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-8"><a href="prefacio.html#cb12-8" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-9"><a href="prefacio.html#cb12-9" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">1</span>, <span class="at">width =</span> <span class="st">&quot;12em&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="prefacio.html#cb12-10" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">column_spec</span>(<span class="dv">2</span>, <span class="at">width =</span> <span class="st">&quot;12em&quot;</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:conteo-ceros">Table 0.5: </span><span id="tab:conteo-ceros">Table 0.6: </span>Conteo de valores cero por variable numérica
</caption>
<thead>
<tr>
<th style="text-align:left;">
variable
</th>
<th style="text-align:right;">
n_ceros
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 12em; ">
periodo
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
id_orden
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
volumen_lote
</td>
<td style="text-align:right;width: 12em; ">
5
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
costo_transformacion
</td>
<td style="text-align:right;width: 12em; ">
5
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
costo_insumo
</td>
<td style="text-align:right;width: 12em; ">
9
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
categoria_producto
</td>
<td style="text-align:right;width: 12em; ">
0
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
num_insumos
</td>
<td style="text-align:right;width: 12em; ">
8
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
cantidad_insumo_1
</td>
<td style="text-align:right;width: 12em; ">
8
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
cantidad_insumo_2
</td>
<td style="text-align:right;width: 12em; ">
279
</td>
</tr>
<tr>
<td style="text-align:left;width: 12em; ">
duracion_proceso
</td>
<td style="text-align:right;width: 12em; ">
4
</td>
</tr>
</tbody>
</table>
<p>Se identificaron 318 registros con valores en cero distribuidos entre las variables numéricas. Los 279 ceros en <code>cantidad_insumo_2</code> coinciden con el total de órdenes que reportan un solo insumo y corresponden a una condición estructural y esperada del dataset, no a mediciones anómalas. A continuación se identifican las órdenes con valores cero en variables distintas de <code>cantidad_insumo_2</code>:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="prefacio.html#cb13-1" tabindex="-1"></a>cols_excluir <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;cantidad_insumo_2&quot;</span>)</span>
<span id="cb13-2"><a href="prefacio.html#cb13-2" tabindex="-1"></a></span>
<span id="cb13-3"><a href="prefacio.html#cb13-3" tabindex="-1"></a>casos_con_ceros <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb13-4"><a href="prefacio.html#cb13-4" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">if_any</span>(</span>
<span id="cb13-5"><a href="prefacio.html#cb13-5" tabindex="-1"></a>    <span class="fu">where</span>(is.numeric) <span class="sc">&amp;</span> <span class="sc">-</span><span class="fu">all_of</span>(cols_excluir),</span>
<span id="cb13-6"><a href="prefacio.html#cb13-6" tabindex="-1"></a>    <span class="sc">~</span> . <span class="sc">==</span> <span class="dv">0</span></span>
<span id="cb13-7"><a href="prefacio.html#cb13-7" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb13-8"><a href="prefacio.html#cb13-8" tabindex="-1"></a>  <span class="fu">select</span>(id_orden, volumen_lote, costo_transformacion, costo_insumo,</span>
<span id="cb13-9"><a href="prefacio.html#cb13-9" tabindex="-1"></a>         duracion_proceso, num_insumos) <span class="sc">%&gt;%</span></span>
<span id="cb13-10"><a href="prefacio.html#cb13-10" tabindex="-1"></a>  <span class="fu">arrange</span>(costo_transformacion)</span>
<span id="cb13-11"><a href="prefacio.html#cb13-11" tabindex="-1"></a></span>
<span id="cb13-12"><a href="prefacio.html#cb13-12" tabindex="-1"></a>n_casos_cero <span class="ot">&lt;-</span> <span class="fu">nrow</span>(casos_con_ceros)</span>
<span id="cb13-13"><a href="prefacio.html#cb13-13" tabindex="-1"></a></span>
<span id="cb13-14"><a href="prefacio.html#cb13-14" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(casos_con_ceros,</span>
<span id="cb13-15"><a href="prefacio.html#cb13-15" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">&quot;Órdenes con valores cero en variables no estructurales&quot;</span>,</span>
<span id="cb13-16"><a href="prefacio.html#cb13-16" tabindex="-1"></a>             <span class="at">format.args =</span> <span class="fu">list</span>(<span class="at">big.mark =</span> <span class="st">&quot;&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb13-17"><a href="prefacio.html#cb13-17" tabindex="-1"></a>  kableExtra<span class="sc">::</span><span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:casos-con-ceros">Table 0.7: </span><span id="tab:casos-con-ceros">Table 0.8: </span>Órdenes con valores cero en variables no estructurales
</caption>
<thead>
<tr>
<th style="text-align:right;">
id_orden
</th>
<th style="text-align:right;">
volumen_lote
</th>
<th style="text-align:right;">
costo_transformacion
</th>
<th style="text-align:right;">
costo_insumo
</th>
<th style="text-align:right;">
duracion_proceso
</th>
<th style="text-align:right;">
num_insumos
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
566930
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
123.0
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:right;">
584267
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
587628
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
594854
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
584273
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.000000
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
585979
</td>
<td style="text-align:right;">
7350
</td>
<td style="text-align:right;">
5.640275
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
100.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
591391
</td>
<td style="text-align:right;">
2525
</td>
<td style="text-align:right;">
12.492979
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
54.5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
551657
</td>
<td style="text-align:right;">
2100
</td>
<td style="text-align:right;">
23.827177
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
107.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
568828
</td>
<td style="text-align:right;">
375
</td>
<td style="text-align:right;">
53.438830
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
32.0
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p>Se identifican 9 órdenes de producción con valores cero en variables no estructurales. Tras consulta con el área de operaciones, estas órdenes se clasifican en tres categorías causales:</p>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:tabla-causas">Table 0.9: </span><span id="tab:tabla-causas">Table 0.10: </span>Clasificación operativa de las órdenes con valores cero
</caption>
<thead>
<tr>
<th style="text-align:left;">
Categoría
</th>
<th style="text-align:left;">
Causa operativa
</th>
<th style="text-align:right;">
Órdenes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 18em; ">
Órdenes cerradas sin ejecutar
</td>
<td style="text-align:left;width: 28em; ">
Volumen, tiempos y consumos en cero; en la práctica no se trabajaron
</td>
<td style="text-align:right;width: 6em; ">
4
</td>
</tr>
<tr>
<td style="text-align:left;width: 18em; ">
Errores de digitación
</td>
<td style="text-align:left;width: 28em; ">
num_insumos = 0 o cantidad_insumo_1 = NA, configuraciones no válidas del proceso
</td>
<td style="text-align:right;width: 6em; ">
4
</td>
</tr>
<tr>
<td style="text-align:left;width: 18em; ">
Producción no conforme
</td>
<td style="text-align:left;width: 28em; ">
Recursos consumidos asumidos como merma; no se asignaron al producto conforme
</td>
<td style="text-align:right;width: 6em; ">
1
</td>
</tr>
<tr>
<td style="text-align:left;width: 18em; ">
<strong>Total</strong>
</td>
<td style="text-align:left;width: 28em; ">
</td>
<td style="text-align:right;width: 6em; ">
9
</td>
</tr>
</tbody>
</table>
<p>Las tres categorías representan configuraciones no válidas para el análisis de costo unitario: en los tres casos, el costo del insumo no refleja una producción efectiva del producto conforme, por lo que su inclusión distorsionaría los estadísticos descriptivos y las estimaciones inferenciales posteriores.</p>
</div>
<div id="eliminación-de-registros-inválidos" class="section level4 hasAnchor" number="0.0.2.4">
<h4><span class="header-section-number">0.0.2.4</span> Eliminación de registros inválidos<a href="prefacio.html#eliminaci%C3%B3n-de-registros-inv%C3%A1lidos" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Dado que las tres categorías causales convergen en un rasgo común —ausencia de costo de insumo asignable al producto conforme— la variable <code>costo_insumo == 0</code> se adopta como criterio de filtrado.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="prefacio.html#cb14-1" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="prefacio.html#cb14-2" tabindex="-1"></a>  <span class="fu">count</span>(costo_insumo <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="prefacio.html#cb14-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">porcentaje =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   `costo_insumo == 0`     n porcentaje
##   &lt;lgl&gt;               &lt;int&gt;      &lt;dbl&gt;
## 1 FALSE                 395       97.8
## 2 TRUE                    9        2.2</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="prefacio.html#cb16-1" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="prefacio.html#cb16-2" tabindex="-1"></a>  <span class="fu">filter</span>(costo_insumo <span class="sc">!=</span> <span class="dv">0</span>)</span>
<span id="cb16-3"><a href="prefacio.html#cb16-3" tabindex="-1"></a></span>
<span id="cb16-4"><a href="prefacio.html#cb16-4" tabindex="-1"></a>n_filas_final <span class="ot">&lt;-</span> <span class="fu">nrow</span>(datos)</span>
<span id="cb16-5"><a href="prefacio.html#cb16-5" tabindex="-1"></a>n_eliminadas  <span class="ot">&lt;-</span> n_filas_inicial <span class="sc">-</span> n_filas_final</span>
<span id="cb16-6"><a href="prefacio.html#cb16-6" tabindex="-1"></a>pct_eliminadas <span class="ot">&lt;-</span> <span class="fu">round</span>(n_eliminadas <span class="sc">/</span> n_filas_inicial <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb16-7"><a href="prefacio.html#cb16-7" tabindex="-1"></a></span>
<span id="cb16-8"><a href="prefacio.html#cb16-8" tabindex="-1"></a><span class="fu">dim</span>(datos)</span></code></pre></div>
<pre><code>## [1] 395  16</code></pre>
<p>Se eliminaron 9 órdenes (2.2% del total) con <code>costo_insumo == 0</code>. El dataset analítico queda conformado por 395 órdenes, las cuales constituyen la base para todos los análisis posteriores.</p>
</div>
</div>
<div id="conversión-de-tipos" class="section level3 hasAnchor" number="0.0.3">
<h3><span class="header-section-number">0.0.3</span> Conversión de tipos<a href="prefacio.html#conversi%C3%B3n-de-tipos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sobre el dataset ya depurado se ajustan los tipos de las variables cuya representación por defecto no corresponde a su naturaleza analítica:</p>
<ul>
<li>La variable <code>periodo</code> viene como entero <code>YYYYMM</code>; en análisis posteriores se podrá convertir a fecha para análisis de temporalidad, pero en el presente estudio se conserva como texto, dado que no se realizarán análisis de series de tiempo.</li>
<li>La variable <code>num_insumos</code>, restringida a los valores 1 y 2, se trata como factor ordenado.</li>
<li>Las variables <code>tipo_equipo</code>, <code>categoria_producto</code>, <code>equipo_id</code>, <code>modalidad_proceso</code>, <code>insumo_1</code> e <code>insumo_2</code> se convierten a factor para los análisis inferenciales posteriores.</li>
<li>La variable <code>insumo_2</code> requiere además una recodificación explícita de los valores faltantes a la categoría <code>sin_segundo_insumo</code>, dado que el NA no representa un dato perdido sino una característica estructural de la orden (cuando <code>num_insumos &lt; 2</code>).</li>
</ul>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="prefacio.html#cb18-1" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="prefacio.html#cb18-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-3"><a href="prefacio.html#cb18-3" tabindex="-1"></a>    <span class="at">periodo            =</span> <span class="fu">as.character</span>(periodo),</span>
<span id="cb18-4"><a href="prefacio.html#cb18-4" tabindex="-1"></a>    <span class="at">num_insumos        =</span> <span class="fu">factor</span>(num_insumos, <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb18-5"><a href="prefacio.html#cb18-5" tabindex="-1"></a>    <span class="at">tipo_equipo        =</span> <span class="fu">as.factor</span>(tipo_equipo),</span>
<span id="cb18-6"><a href="prefacio.html#cb18-6" tabindex="-1"></a>    <span class="at">categoria_producto =</span> <span class="fu">as.factor</span>(categoria_producto),</span>
<span id="cb18-7"><a href="prefacio.html#cb18-7" tabindex="-1"></a>    <span class="at">equipo_id          =</span> <span class="fu">as.factor</span>(equipo_id),</span>
<span id="cb18-8"><a href="prefacio.html#cb18-8" tabindex="-1"></a>    <span class="at">modalidad_proceso  =</span> <span class="fu">as.factor</span>(modalidad_proceso),</span>
<span id="cb18-9"><a href="prefacio.html#cb18-9" tabindex="-1"></a>    <span class="at">insumo_1           =</span> <span class="fu">as.factor</span>(insumo_1),</span>
<span id="cb18-10"><a href="prefacio.html#cb18-10" tabindex="-1"></a>    <span class="at">insumo_2           =</span> <span class="fu">factor</span>(<span class="fu">if_else</span>(<span class="fu">is.na</span>(insumo_2), <span class="st">&quot;sin_segundo_insumo&quot;</span>, insumo_2))</span>
<span id="cb18-11"><a href="prefacio.html#cb18-11" tabindex="-1"></a>  )</span>
<span id="cb18-12"><a href="prefacio.html#cb18-12" tabindex="-1"></a></span>
<span id="cb18-13"><a href="prefacio.html#cb18-13" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div>
<pre><code>## tibble [395 × 16] (S3: tbl_df/tbl/data.frame)
##  $ periodo             : chr [1:395] &quot;202501&quot; &quot;202501&quot; &quot;202501&quot; &quot;202501&quot; ...
##  $ codigo_producto     : chr [1:395] &quot;P05747&quot; &quot;P06976&quot; &quot;P07920&quot; &quot;P07767&quot; ...
##  $ id_orden            : num [1:395] 546009 551645 548767 552185 546482 ...
##  $ volumen_lote        : num [1:395] 7440 1680 1556 2700 2578 ...
##  $ costo_transformacion: num [1:395] 24.6 36.5 22.3 14.2 18.2 ...
##  $ costo_insumo        : num [1:395] 4.18 1.59 2.15 3.84 2.08 ...
##  $ equipo_id           : Factor w/ 12 levels &quot;M02&quot;,&quot;M04&quot;,&quot;M05&quot;,..: 4 1 9 8 1 1 1 1 1 6 ...
##  $ tipo_equipo         : Factor w/ 4 levels &quot;A1&quot;,&quot;B2&quot;,&quot;C3&quot;,..: 1 2 1 1 2 2 2 2 2 3 ...
##  $ categoria_producto  : Factor w/ 7 levels &quot;1&quot;,&quot;2&quot;,&quot;3&quot;,&quot;4&quot;,..: 7 5 5 5 5 5 5 5 5 4 ...
##  $ num_insumos         : Ord.factor w/ 2 levels &quot;1&quot;&lt;&quot;2&quot;: 1 2 1 1 2 2 2 2 1 1 ...
##  $ insumo_1            : Factor w/ 6 levels &quot;A_T&quot;,&quot;B_T&quot;,&quot;N_O&quot;,..: 2 2 3 2 2 2 2 2 5 3 ...
##  $ insumo_2            : Factor w/ 7 levels &quot;A_T&quot;,&quot;B_T&quot;,&quot;N_O&quot;,..: 6 4 6 6 7 7 7 7 6 6 ...
##  $ cantidad_insumo_1   : num [1:395] 6 1.5 0.5 2 2 2 2 2 1.3 2.5 ...
##  $ cantidad_insumo_2   : num [1:395] 0 0.05 0 0 0.05 0.05 0.05 0.5 0 0 ...
##  $ modalidad_proceso   : Factor w/ 3 levels &quot;X&quot;,&quot;Y&quot;,&quot;Z&quot;: 1 2 2 1 1 1 1 1 2 1 ...
##  $ duracion_proceso    : num [1:395] 300 98 100 62 91 ...</code></pre>
<p>Tras la conversión, las variables categóricas quedan representadas como factores, el factor ordenado <code>num_insumos</code> preserva la jerarquía natural de sus niveles, y la categoría <code>sin_segundo_insumo</code> de <code>insumo_2</code> absorbe las ausencias estructurales sin pérdida de observaciones.</p>
</div>
<div id="consideraciones-estructurales-para-el-análisis" class="section level3 hasAnchor" number="0.0.4">
<h3><span class="header-section-number">0.0.4</span> Consideraciones estructurales para el análisis<a href="prefacio.html#consideraciones-estructurales-para-el-an%C3%A1lisis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Antes de entrar al análisis exploratorio, vale la pena dejar claros algunos puntos sobre la estructura del dataset depurado, ya que pueden prestarse a malas interpretaciones.</p>
<ul>
<li>La variable cantidad_insumo_2 toma el valor cero cuando num_insumos = 1. Esto significa simplemente ese insumo 2 no existe en ese caso. Son ceros “estructurales” .</li>
<li>Los costos costo_transformacion y costo_insumo están definidos como valores monetarios por unidad de producto. Permitiendo comparar directamente entre órdenes, sin importar el tamaño del lote, ya que no requieren ajustes por escala de producción.</li>
</ul>
<p>El dataset con el que se trabajará está compuesto por r n_filas_final órdenes de producción. Sobre esta base se desarrollan los análisis exploratorios e inferenciales de los siguientes capítulos.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="prefacio.html#cb20-1" tabindex="-1"></a><span class="co"># Para auditoría y reproducibilidad externa</span></span>
<span id="cb20-2"><a href="prefacio.html#cb20-2" tabindex="-1"></a><span class="fu">write_csv2</span>(datos, <span class="st">&quot;data/data_costos_limpio.csv&quot;</span>)</span>
<span id="cb20-3"><a href="prefacio.html#cb20-3" tabindex="-1"></a></span>
<span id="cb20-4"><a href="prefacio.html#cb20-4" tabindex="-1"></a><span class="co"># Para cargar rápido en capítulos posteriores preservando tipos</span></span>
<span id="cb20-5"><a href="prefacio.html#cb20-5" tabindex="-1"></a><span class="fu">saveRDS</span>(datos, <span class="st">&quot;data/data_costos_limpio.rds&quot;</span>)</span></code></pre></div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="portada.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="diccionario-de-campos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "serif",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": {},
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "toolbar": {
    "position": "static"
  }
});
});
</script>

</body>

</html>
